include:
    - ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/task_queue/rq/development/api.withrq.docker-compose.yml

x-logging-settings: &logging-settings
    logging:
        driver: "json-file"
        options:
            max-size: "256k"
            max-file: "3"

services:
    web:
        image: ${APP_NAME}-development-web:${DOCKER_COMPOSE_BUILD_TAG}
        build:
            context: ${DOCKER_COMPOSE_PROJECT_ROOT}/web/
            dockerfile: Dockerfile
            target: ${DOCKER_COMPOSE_WEB_BUILD_TARGET}
            tags:
                - ${APP_NAME}-development-web:${DOCKER_COMPOSE_BUILD_TAG}
            args:
                APP_NAME: ${APP_NAME}
                APP_TITLE: ${APP_TITLE}
                DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
                PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS: ${PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS}
                SCHEME: ${SCHEME}
                SERVER_PORT: ${SERVER_PORT}
                WEB_HOST: ${WEB_HOST}
                WEB_PORT: ${WEB_PORT}
        restart: unless-stopped
        container_name: ${APP_NAME}-web-${USER}
        depends_on:
            - api
        <<: *logging-settings
        environment:
            APP_NAME: ${APP_NAME}
            APP_TITLE: ${APP_TITLE}
            DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
            IBM_TELEMETRY_DISABLED: true
            PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS: ${PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS}
            SCHEME: ${SCHEME}
            SERVER_PORT: ${SERVER_PORT}
            WEB_HOST: ${WEB_HOST}
            WEB_PORT: ${WEB_PORT}
        ports:
            - ${WEB_PORT}:3000
        volumes:
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/web/ui:/apps/${APP_NAME}/
