services:  
  swagger:
      image: ${APP_NAME}-swagger-ui:${DOCKER_COMPOSE_BUILD_TAG}
      build:
        context: ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/swagger/builder/
        dockerfile: Dockerfile
        tags:
          - ${APP_NAME}-swagger-ui:${DOCKER_COMPOSE_BUILD_TAG}
        args:
          - APP_NAME=${APP_NAME}
          - SERVER_HOST=${SERVER_HOST}
          - SERVER_PORT=${SERVER_PORT}
      ports:
        - ${SWAGGER_PORT}:8080
      environment:
        - SWAGGER_JSON=/swagger/swagger.yml