# Generated by Django 5.0.2 on 2026-01-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=512, unique=True)),
                ("content", models.JSONField()),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "content",
                "db_table_comment": """
    `Content` represent dynamic content that may appear
    in `BI Portal`'s UI.

    A `Content` instance includes:
      * id (int): An auto-generated number managed by the database.
      * key (models.CharField): An alias for dynamic content.
      * content (models.JSONField): Dynamic content for `BI Portal`.
      * created (models.DateTimeField): The date & time this `Content` was created.
      * modified (models.DateTimeField): The date & time this `Content` was modified.
      * modified_by (contrib.auth.models.User): A `BI Portal` user.
    """,
                "ordering": ["-modified"],
                "default_related_name": "content",
                "indexes": [
                    models.Index(fields=["key"], name="content_key"),
                    models.Index(fields=["id"], name="content_id"),
                ],
            },
        ),
    ]
