openapi: 3.0.0
info:
  title: "Enter info title here."
  version: "1.0"
servers:
  - url: "Enter server URL here."
tags:
  - name: "Enter tag name here."
  - description: "Enter description here."

paths:
  /analytics/visits:
    post:
      tags:
        - "analytics.visit.create"
      summary: "Create a Visit."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateVisitRequest"
      responses:
        "201":
          description: "CREATED"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CreateVisitResponse"
        "401":
          description: "UNAUTHORIZED"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CreateVisitUnAuthorizedResponse"              
        "404":
          description: "Resource does not exist."
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CreateVisitResourceDoesNotExistErrorResponse"
  /directory/resources/search?page={page_number}&limit={search_limit}:
    post:
      tags:
        - "directory.resources.search"
      summary: "Search for Resources."
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Page number to select from a paginated response of
            `Resource` records.
        - in: query
          name: limit
          schema:
            type: integer
          description: Maximum number of `Resource` records to return.
        
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResourceSearchRequest"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResourceSearchFunctreeStructureSerializedResponse"
                  - $ref: "#/components/schemas/ResourceSearchDefaultStructureResponse"
                 
        "400":
          description: "Missing parameter or invalid parameter."
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/ResourceSearchMissingParameterErrorResponse"
                  - $ref: "#/components/schemas/ResourceSearchInvalidParameterErrorResponse"
  /directory/employee-levels?id={employee_level_id}:
    get:
      tags:
        - "directory.employeelevel.fetch"
      summary: "Fetch EmployeeLevel(s)."
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: Primary key of the `EmployeeLevel` record
            to fetch.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/FetchEmployeeLevelsResponse"
                  - $ref: "#/components/schemas/FetchEmployeeLevelByIdResponse"                 
        "404":
          description: "Employee Level does not exist for given id."
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/FetchEmployeeLevelByIdDoesNotExistResponse"
  /directory/subfunctions?id={subfunction}:
    get:
      tags:
        - "directory.subfunction.fetch"
      summary: "Fetch SubFunction(s)."
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: Primary key of the `SubFunction` record
            to fetch.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/FetchSubFunctionsResponse"
                  - $ref: "#/components/schemas/FetchSubFunctionByIdResponse"                 
        "404":
          description: "SubFunction does not exist for given id."
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/FetchSubFunctionByIdDoesNotExistResponse"
  /directory/tags/search?label={label}:
    get:
      tags:
        - "directory.tag.search"
      summary: "Search for Tags based on the given label."
      parameters:
        - in: query
          name: label
          schema:
            type: string
          description: Label that will be used to search for Tags.
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/SearchTagsResponse"
       
components:
  schemas:
    CreateVisitRequest:
      title: "Create `Visit` request."
      type: object
      properties:
        resource:
          type: integer
          description: Id of the `Resource` that is being
            visited.
          default: 1
    
    CreateVisitResponse:
      title: "Create `Visit` response."
      type: object
      properties:
        data:
          type: object
          description: The created `Visit`.
          example:
            {
              "id": 1,
              "resource": {
                  "id": 1,
                  "uid": "00000000-0000-0000-0000-000000000000",
                  "previous_revision": null,
                  "revision_number": 0,
                  "name": "Resource 1 Name",
                  "description": "Resource 1 Description.",
                  "url": "www.example.com",
                  "thumbnail": "/path/to/resource/thumbnail",
                  "employee_levels": [
                    {
                      "id": 1,
                      "name": "Employee Level 1 Name",
                      "created": "1970-01-01T12:00:00-04:00",
                      "modified": "1970-01-01T12:00:00-04:00",
                    },
                    ...
                  ],
                  "subfunctions": [
                    {
                      "id": 1,                   
                      "name": "Function 1 SubFunction 1 Name",
                      "description": "Function 1 SubFunction 1 Description.",
                      "function": {
                        "id": 1,
                        "name": "Function 1 Name",
                        "description": "Function 1 Description.",
                        "created": "1970-01-01T12:00:00-04:00",
                        "modified": "1970-01-01T12:00:00-04:00",
                      },
                      "created": "1970-01-01T12:00:00-04:00",
                      "modified": "1970-01-01T12:00:00-04:00",
                    },
                    ...
                  ],
                  "tags": [
                    {
                      "id": 1,
                      "created": "1970-01-01T12:00:00-04:00",
                      "modified": "1970-01-01T12:00:00-04:00",
                      "label": "filter::site:Test",
                    },
                    ...
                  ],
                  "type": "Resource Type 1",
                  "download": false,
                  "active": true,
                  "created": "1970-01-01T12:00:00-04:00",
                },
              "user": "Test.User@harris.com"
            }

    CreateVisitUnAuthorizedResponse:
      title: "Create `Visit` error response due to unauthorized access."
      example: "Not authorized to access resource."
    
    CreateVisitResourceDoesNotExistErrorResponse:
      title: "Create `Visit` error response due to supplying an id
        for a `Resource` that does not exist."
      example: "Resource (id=resource_id), does not exist."

    ResourceSearchRequest:
      title: "`Resource` search request."
      type: object
      properties:
        name:
          type: string
          description: Name of the `Resource`.
          default: ''         
        description:
          type: string
          description: Description of the `Resource`.
          default: ''
        functions:
          type: array[int]          
          description:
            A list of `Function` ids related to `SubFunction`s related to a `Resource`.
          default: []
        subfunctions:
          type: array[int]
          description:
            A list of `SubFunction` ids related to a `Resource`.
          default: []
        employee_levels:
          type: array[int]
          default: []
          description:
            A list of `EmployeeLevel` ids related to a `Resource`.
        tags:
          type: array[int]
          description:
            A list of `Tag` ids related to a `Resource`.
          default: []
        download:
          type: boolean
          description:
            Indicates whether a `Resource` should be downloadable
            or not.
          default: null
        structure:
          type: string
          description:
            "Indicates the structure of the search response.
            Accepted values: default, functree."
          default: default       
    ResourceSearchDefaultStructureResponse:
      title: "`Resource` search response with `default` structure."
      type: object
      properties:
        data:
          type: array
          description: A collection of serialized `Resource`s that match the search criteria.
          items:
            type: object
          example:
            [
              {
                "id": 1,
                "uid": "00000000-0000-0000-0000-000000000000",
                "previous_revision": null,
                "revision_number": 0,
                "name": "Resource 1 Name",
                "description": "Resource 1 Description.",
                "url": "www.example.com",
                "thumbnail": "/path/to/resource/thumbnail",
                "employee_levels": [
                  {
                    "id": 1,
                    "name": "Employee Level 1 Name",
                    "created": "1970-01-01T12:00:00-04:00",
                    "modified": "1970-01-01T12:00:00-04:00",
                  },
                  ...
                ],
                "subfunctions": [
                  {
                    "id": 1,                   
                    "name": "Function 1 SubFunction 1 Name",
                    "description": "Function 1 SubFunction 1 Description.",
                    "function": {
                      "id": 1,
                      "name": "Function 1 Name",
                      "description": "Function 1 Description.",
                      "created": "1970-01-01T12:00:00-04:00",
                      "modified": "1970-01-01T12:00:00-04:00",
                    },
                    "created": "1970-01-01T12:00:00-04:00",
                    "modified": "1970-01-01T12:00:00-04:00",
                  },
                  ...
                ],
                "tags": [
                  {
                    "id": 1,
                    "created": "1970-01-01T12:00:00-04:00",
                    "modified": "1970-01-01T12:00:00-04:00",
                    "label": "filter::site:Test",
                  },
                  ...
                ],
                "type": "Resource Type 1",
                "download": false,
                "active": true,
                "created": "1970-01-01T12:00:00-04:00",
              },
              ...
            ]

    ResourceSearchFunctreeStructureSerializedResponse:
      title: "`Resource` search response with `functree` structure and serialized `Resource`s."
      type: object
      properties:
        data:
          type: object
          description: 
            A collection of serialized `Resource`s grouped by their `SubFunction`s and their
            respective parent `Function`s.         
          example:           
            {
              "Function 1 Name": {
                "Function 1 SubFunction 1 Name": [
                  {
                    "id": 1,
                    "uid": "00000000-0000-0000-0000-000000000000",
                    "previous_revision": null,
                    "revision_number": 0,
                    "name": "Resource 1 Name",
                    "description": "Resource 1 Description.",
                    "url": "www.example.com",
                    "thumbnail": "/path/to/resource/thumbnail",
                    "employee_levels": [
                      {
                        "id": 1,
                        "name": "Employee Level 1 Name",
                        "created": "1970-01-01T12:00:00-04:00",
                        "modified": "1970-01-01T12:00:00-04:00",
                      },
                      ...
                    ],
                    "subfunctions": [
                      {
                        "id": 1,                        
                        "name": "Function 1 SubFunction 1 Name",
                        "description": "Function 1 SubFunction 1 Description.",
                        "function": {
                          "id": 1,
                          "name": "Function 1 Name",
                          "description": "Function 1 Description.",
                          "created": "1970-01-01T12:00:00-04:00",
                          "modified": "1970-01-01T12:00:00-04:00",
                        },
                        "created": "1970-01-01T12:00:00-04:00",
                        "modified": "1970-01-01T12:00:00-04:00",
                      },
                      ...
                    ],
                    "tags": [
                      {
                        "id": 1,
                        "created": "1970-01-01T12:00:00-04:00",
                        "modified": "1970-01-01T12:00:00-04:00",
                        "label": "filter::site:Test",
                      },
                      ...
                    ],
                    "type": "Resource Type 1",
                    "download": false,
                    "active": true,
                    "created": "1970-01-01T12:00:00-04:00",
                    "favorited_by": ["Some.User@harris.com", "Test.User@harris.com", ...],
                    "site": ["Location 1", "Location 2", ...],
                    "restricted": {"department": ["Department 1",...], ...}
                  },
                  ...
                ],
                ...
              },
              ...
            }
  
    ResourceSearchMissingParameterErrorResponse:
      title: "`Resource` search error response due to a missing parameter."      
      example: "Missing parameter: `name` from search parameters."

    ResourceSearchInvalidParameterErrorResponse:
      title: "`Resource` search error response due to an invalid parameter."
      example: "Incorrect value given for a search parameter."
    
    FetchEmployeeLevelsResponse:
      title: "Fetch `EmployeeLevel` response."
      type: object
      properties:
        data:
          type: array
          items:
            type: object
          example:
            [
              {
                "id": 1,
                "name": "Employee Level 1 Name",
                "description": "Employee Level 1 Description.",
                "created": "1970-01-27T12:00:00-04:00",
                "modified": "1970-01-27T12:00:00-04:00",
                "level": 1
              },
              {
                "id": 2,
                "name": "Employee Level 2 Name",
                "description": "Employee Level 2 Description.",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "level": 2
              },
              ...
            ]
  
    FetchEmployeeLevelByIdResponse:
      title: "Fetch `EmployeeLevel` by id response."
      type: object
      properties:
        data:
          type: object
          example:
            {
              "id": 1,
              "name": "Employee Level 1 Name",
              "description": "Employee Level 1 Description.",
              "created": "1970-01-27T12:00:00-04:00",
              "modified": "1970-01-27T12:00:00-04:00",
              "level": 1
            }
      
    FetchEmployeeLevelByIdDoesNotExistResponse:
      title: "Fetch `EmployeeLevel` error response due to using an id that
        does not exist."
      example: "Employee Level (id=employee_level_id), does not exist."

    FetchSubFunctionsResponse:
      title: "Fetch `SubFunction` response."
      type: object
      properties:
        data:
          type: array
          items:
            type: object
          example:
            [
              {
                "id": 1,
                "function": {
                  "id": 1,
                  "name": "Function 1 Name",
                  "description": "Function 1 Description.",
                  "created": "2024-08-27T12:00:00-04:00",
                  "modified": "2024-08-27T12:00:00-04:00"
                },
                "name": "SubFunction 1 Name",
                "description": "Function 1 SubFunction 1.",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00"
              },
              {
                "id": 2,
                "function": {
                  "id": 1,
                  "name": "Function 1 Name",
                  "description": "Function 1 Description.",
                  "created": "2024-08-27T12:00:00-04:00",
                  "modified": "2024-08-27T12:00:00-04:00"
                },
                "name": "SubFunction 2 Name",
                "description": "Function 1 SubFunction 2.",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00"
              },
              ...
            ]
  
    
    FetchSubFunctionByIdResponse:
      title: "Fetch `SubFunction` by id response."
      type: object
      properties:
        data:
          type: object
          example:
            {
              "id": 1,
              "function": {
                "id": 1,
                "name": "Function 1 Name",
                "description": "Function 1 Description.",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00"
              },
              "name": "SubFunction 1 Name",
              "description": "Function 1 SubFunction 1.",
              "created": "2024-08-27T12:00:00-04:00",
              "modified": "2024-08-27T12:00:00-04:00"
            }
                
    FetchSubFunctionByIdDoesNotExistResponse:
      title: "Fetch `SubFunction` error response due to using an id that
        does not exist."
      example: "SubFunction (id=subfunction_id), does not exist."

    SearchTagsResponse:
      title: "Search `Tag`s response."
      type: object
      properties:
        data:
          type: array
          items:
            type: object
          example:
            [
              {
                "id": 1,
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "label": "filter::site:Melbourne"
              },
              {
                "id": 2,
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "label": "filter::site:Rochester"
              },
              ...
            ]

          



