import {
  IRecord,
  assessmentOptions,
} from "views/definitions/ProgramReviewTool.types";

function getCurrentYearMonth(subtractMonths = 0): number {
  const now = new Date();
  now.setMonth(now.getMonth() - subtractMonths);
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0"); // still string for concatenation
  return Number(`${year}${month}`);
}

export const reportingPeriods: number[] = [
  getCurrentYearMonth(),
  getCurrentYearMonth(1),
];


export const PATestData: { [key: string]: IRecord[] } = {
  PA1: [
    {
      id: 1,
      name: "Program 1",
      sector: "Airborne Combat Sytems",
      division: "Electronic Warfare",
      tier: 1,
      contractType: "Type 1",
      contractValue: 5823400,
      contractNumber: "384756",
      contractStartDate: "11/15/2023",
      contractEndDate: "11/14/2027",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase1",
      site: "City1/State1",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement1",
      budgetedCostWorkScheduledCumulative: 10000,
      budgetedCostWorkPerformedCumulative: 20000,
      actualCostWorkPerformedCumulative: 15000,
      budgetAtComplete: 30000,
      estimateAtComplete: 25000,
      estimateToComplete: 5000,
      managementReserve: 2000,
      weightedRisksAndOpportunities: 1000,
      schedulePerformanceIndexCumulative: 0.9,
      costPerformanceIndexCumulative: 0.85,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.YELLOW,
      riskAssessment: assessmentOptions.RED,
      overallProgram: assessmentOptions.BLUE,
      comments: "Comment1",
      previousRevision: null,
      program: null,
      user: null,
      paNumber: "",
      created: ""
    },
    {
      id: 2,
      name: "Program 1",
      sector: "Airborne Combat Sytems",
      division: "Electronic Warfare",
      tier: 1,
      contractType: "Type 1",
      contractValue: 582340,
      contractNumber: "384756",
      contractStartDate: "11/15/2023",
      contractEndDate: "11/14/2027",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase1",
      site: "City1/State1",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement1",
      budgetedCostWorkScheduledCumulative: 1050,
      budgetedCostWorkPerformedCumulative: 2050,
      actualCostWorkPerformedCumulative: 1550,
      budgetAtComplete: 3050,
      estimateAtComplete: 2550,
      estimateToComplete: 550,
      managementReserve: 250,
      weightedRisksAndOpportunities: 150,
      schedulePerformanceIndexCumulative: 0.92,
      costPerformanceIndexCumulative: 0.87,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.RED,
      comments: "Comment2",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
  PA2: [
    {
      id: 3,
      name: "Program 2",
      sector: "Intelligence & Cyber",
      division: "Microelectronics",
      tier: 2,
      contractType: "Type 1",
      contractValue: 745120,
      contractNumber: "592847",
      contractStartDate: "12/01/2023",
      contractEndDate: "11/30/2027",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase2",
      site: "City2/State2",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement2",
      budgetedCostWorkScheduledCumulative: 1100,
      budgetedCostWorkPerformedCumulative: 2100,
      actualCostWorkPerformedCumulative: 1600,
      budgetAtComplete: 3100,
      estimateAtComplete: 2600,
      estimateToComplete: 600,
      managementReserve: 300,
      weightedRisksAndOpportunities: 200,
      schedulePerformanceIndexCumulative: 0.95,
      costPerformanceIndexCumulative: 0.9,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.RED,
      comments: "Comment3",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 4,
      name: "Program 2",
      sector: "Intelligence & Cyber",
      division: "Microelectronics",
      tier: 2,
      contractType: "Type 1",
      contractValue: 745120,
      contractNumber: "592847",
      contractStartDate: "12/01/2023",
      contractEndDate: "11/30/2027",
      reportingPeriod: 2025008,
      teamMembers: [],
      programPhase: "Phase2",
      site: "City2/State2",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement2",
      budgetedCostWorkScheduledCumulative: 1150,
      budgetedCostWorkPerformedCumulative: 2150,
      actualCostWorkPerformedCumulative: 1650,
      budgetAtComplete: 3150,
      estimateAtComplete: 2650,
      estimateToComplete: 650,
      managementReserve: 350,
      weightedRisksAndOpportunities: 250,
      schedulePerformanceIndexCumulative: 0.97,
      costPerformanceIndexCumulative: 0.92,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.RED,
      comments: "Comment3",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
  PA3: [
    {
      id: 5,
      name: "Program 3",
      sector: "Mission Networks",
      division: "Managed Services",
      tier: 3,
      contractType: "Type 1",
      contractValue: 1298500,
      contractNumber: "748392",
      contractStartDate: "01/10/2024",
      contractEndDate: "01/09/2028",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase3",
      site: "City3/State3",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement3",
      budgetedCostWorkScheduledCumulative: 1200,
      budgetedCostWorkPerformedCumulative: 2200,
      actualCostWorkPerformedCumulative: 1700,
      budgetAtComplete: 3200,
      estimateAtComplete: 2700,
      estimateToComplete: 700,
      managementReserve: 400,
      weightedRisksAndOpportunities: 300,
      schedulePerformanceIndexCumulative: 1.0,
      costPerformanceIndexCumulative: 0.95,
      customerAssessment: assessmentOptions.YELLOW,
      technicalAssessment: assessmentOptions.BLUE,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.RED,
      comments: "Comment4",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 6,
      name: "Program 3",
      sector: "Mission Networks",
      division: "Managed Services",
      tier: 3,
      contractType: "Type 1",
      contractValue: 1298500,
      contractNumber: "748392",
      contractStartDate: "01/10/2024",
      contractEndDate: "01/09/2028",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase3",
      site: "City3/State3",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement3",
      budgetedCostWorkScheduledCumulative: 1250,
      budgetedCostWorkPerformedCumulative: 2250,
      actualCostWorkPerformedCumulative: 1750,
      budgetAtComplete: 3250,
      estimateAtComplete: 2750,
      estimateToComplete: 750,
      managementReserve: 450,
      weightedRisksAndOpportunities: 350,
      schedulePerformanceIndexCumulative: 1.02,
      costPerformanceIndexCumulative: 0.97,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.RED,
      comments: "Comment4",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
  PA4: [
    {
      id: 7,
      name: "Program 4",
      sector: "Space Systems",
      division: "Spectral Solutions",
      tier: 4,
      contractType: "Type 1",
      contractValue: 987650,
      contractNumber: "182736",
      contractStartDate: "02/20/2024",
      contractEndDate: "02/19/2028",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase4",
      site: "City4/State4",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement4",
      budgetedCostWorkScheduledCumulative: 1300,
      budgetedCostWorkPerformedCumulative: 2300,
      actualCostWorkPerformedCumulative: 1800,
      budgetAtComplete: 3300,
      estimateAtComplete: 2800,
      estimateToComplete: 800,
      managementReserve: 500,
      weightedRisksAndOpportunities: 400,
      schedulePerformanceIndexCumulative: 1.05,
      costPerformanceIndexCumulative: 1.0,
      customerAssessment: assessmentOptions.RED,
      technicalAssessment: assessmentOptions.YELLOW,
      riskAssessment: assessmentOptions.BLUE,
      overallProgram: assessmentOptions.RED,
      comments: "Comment5",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 8,
      name: "Program 4",
      sector: "Space Systems",
      division: "Spectral Solutions",
      tier: 4,
      contractType: "Type 1",
      contractValue: 987650,
      contractNumber: "182736",
      contractStartDate: "02/20/2024",
      contractEndDate: "02/19/2028",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase4",
      site: "City4/State4",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement4",
      budgetedCostWorkScheduledCumulative: 1350,
      budgetedCostWorkPerformedCumulative: 2350,
      actualCostWorkPerformedCumulative: 1850,
      budgetAtComplete: 3350,
      estimateAtComplete: 2850,
      estimateToComplete: 850,
      managementReserve: 550,
      weightedRisksAndOpportunities: 450,
      schedulePerformanceIndexCumulative: 1.07,
      costPerformanceIndexCumulative: 1.02,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.YELLOW,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.YELLOW,
      comments: "Comment6",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
  PA5: [
    {
      id: 9,
      name: "Program 5",
      sector: "Airborne Combat Sytems",
      division: "Military Avionics",
      tier: 2,
      contractType: "Type 2",
      contractValue: 432900,
      contractNumber: "927384",
      contractStartDate: "03/05/2024",
      contractEndDate: "03/04/2028",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase5",
      site: "City5/State5",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement5",
      budgetedCostWorkScheduledCumulative: 1400,
      budgetedCostWorkPerformedCumulative: 2400,
      actualCostWorkPerformedCumulative: 1900,
      budgetAtComplete: 3400,
      estimateAtComplete: 2900,
      estimateToComplete: 900,
      managementReserve: 600,
      weightedRisksAndOpportunities: 500,
      schedulePerformanceIndexCumulative: 1.1,
      costPerformanceIndexCumulative: 1.05,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.RED,
      comments: "Comment7",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 10,
      name: "Program 5",
      sector: "Airborne Combat Sytems",
      division: "Military Avionics",
      tier: 2,
      contractType: "Type 2",
      contractValue: 432900,
      contractNumber: "927384",
      contractStartDate: "03/05/2024",
      contractEndDate: "03/04/2028",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase5",
      site: "City5/State5",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement5",
      budgetedCostWorkScheduledCumulative: 1450,
      budgetedCostWorkPerformedCumulative: 2450,
      actualCostWorkPerformedCumulative: 1950,
      budgetAtComplete: 3450,
      estimateAtComplete: 2950,
      estimateToComplete: 950,
      managementReserve: 650,
      weightedRisksAndOpportunities: 550,
      schedulePerformanceIndexCumulative: 1.12,
      costPerformanceIndexCumulative: 1.08,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.YELLOW,
      comments: "Comment8",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
  PA6: [
    {
      id: 11,
      name: "Program 6",
      sector: "Intelligence & Cyber",
      division: "Tactical Missions",
      tier: 2,
      contractType: "Type 2",
      contractValue: 1120430,
      contractNumber: "564738",
      contractStartDate: "04/12/2024",
      contractEndDate: "04/11/2029",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase6",
      site: "City6/State6",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement6",
      budgetedCostWorkScheduledCumulative: 1500,
      budgetedCostWorkPerformedCumulative: 2500,
      actualCostWorkPerformedCumulative: 2000,
      budgetAtComplete: 3500,
      estimateAtComplete: 3000,
      estimateToComplete: 1000,
      managementReserve: 400,
      weightedRisksAndOpportunities: 300,
      schedulePerformanceIndexCumulative: 0.98,
      costPerformanceIndexCumulative: 1.0,
      customerAssessment: assessmentOptions.YELLOW,
      technicalAssessment: assessmentOptions.BLUE,
      riskAssessment: assessmentOptions.RED,
      overallProgram: assessmentOptions.RED,
      comments: "Comment9",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 12,
      name: "Program 6",
      sector: "Intelligence & Cyber",
      division: "Tactical Missions",
      tier: 2,
      contractType: "Type 2",
      contractValue: 1120430,
      contractNumber: "564738",
      contractStartDate: "04/12/2024",
      contractEndDate: "04/11/2029",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase6",
      site: "City6/State6",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement6",
      budgetedCostWorkScheduledCumulative: 1550,
      budgetedCostWorkPerformedCumulative: 2550,
      actualCostWorkPerformedCumulative: 2050,
      budgetAtComplete: 3550,
      estimateAtComplete: 3050,
      estimateToComplete: 1050,
      managementReserve: 450,
      weightedRisksAndOpportunities: 350,
      schedulePerformanceIndexCumulative: 1.0,
      costPerformanceIndexCumulative: 1.03,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.YELLOW,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.YELLOW,
      comments: "Comment10",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],

  PA7: [
    {
      id: 13,
      name: "Program 7",
      sector: "Mission Networks",
      division: "Automation Solutions",
      tier: 2,
      contractType: "Type 2",
      contractValue: 678240,
      contractNumber: "839201",
      contractStartDate: "05/28/2024",
      contractEndDate: "05/27/2029",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase7",
      site: "City7/State7",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement7",
      budgetedCostWorkScheduledCumulative: 1600,
      budgetedCostWorkPerformedCumulative: 2600,
      actualCostWorkPerformedCumulative: 2100,
      budgetAtComplete: 3600,
      estimateAtComplete: 3100,
      estimateToComplete: 1100,
      managementReserve: 500,
      weightedRisksAndOpportunities: 400,
      schedulePerformanceIndexCumulative: 1.05,
      costPerformanceIndexCumulative: 1.04,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.GREEN,
      comments: "Comment11",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 14,
      name: "Program 7",
      sector: "Mission Networks",
      division: "Automation Solutions",
      tier: 2,
      contractType: "Type 2",
      contractValue: 678240,
      contractNumber: "839201",
      contractStartDate: "05/28/2024",
      contractEndDate: "05/27/2029",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase7",
      site: "City7/State7",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement7",
      budgetedCostWorkScheduledCumulative: 1650,
      budgetedCostWorkPerformedCumulative: 2650,
      actualCostWorkPerformedCumulative: 2150,
      budgetAtComplete: 3650,
      estimateAtComplete: 3150,
      estimateToComplete: 1150,
      managementReserve: 550,
      weightedRisksAndOpportunities: 450,
      schedulePerformanceIndexCumulative: 1.07,
      costPerformanceIndexCumulative: 1.06,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.BLUE,
      overallProgram: assessmentOptions.GREEN,
      comments: "Comment12",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],

  PA8: [
    {
      id: 15,
      name: "Program 8",
      sector: "Space Systems",
      division: "Surveillance Systems",
      tier: 2,
      contractType: "Type 2",
      contractValue: 823590,
      contractNumber: "475920",
      contractStartDate: "06/15/2024",
      contractEndDate: "06/14/2029",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase8",
      site: "City8/State8",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement8",
      budgetedCostWorkScheduledCumulative: 1700,
      budgetedCostWorkPerformedCumulative: 2700,
      actualCostWorkPerformedCumulative: 2200,
      budgetAtComplete: 3700,
      estimateAtComplete: 3200,
      estimateToComplete: 1200,
      managementReserve: 600,
      weightedRisksAndOpportunities: 500,
      schedulePerformanceIndexCumulative: 0.96,
      costPerformanceIndexCumulative: 0.95,
      customerAssessment: assessmentOptions.RED,
      technicalAssessment: assessmentOptions.RED,
      riskAssessment: assessmentOptions.RED,
      overallProgram: assessmentOptions.RED,
      comments: "Comment13",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 16,
      name: "Program 8",
      sector: "Space Systems",
      division: "Surveillance Systems",
      tier: 2,
      contractType: "Type 2",
      contractValue: 823590,
      contractNumber: "475920",
      contractStartDate: "06/15/2024",
      contractEndDate: "06/14/2029",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase8",
      site: "City8/State8",
      defenseFinancialAcquisitionRegulationClause: false,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement8",
      budgetedCostWorkScheduledCumulative: 1750,
      budgetedCostWorkPerformedCumulative: 2750,
      actualCostWorkPerformedCumulative: 2250,
      budgetAtComplete: 3750,
      estimateAtComplete: 3250,
      estimateToComplete: 1250,
      managementReserve: 650,
      weightedRisksAndOpportunities: 550,
      schedulePerformanceIndexCumulative: 0.98,
      costPerformanceIndexCumulative: 0.97,
      customerAssessment: assessmentOptions.YELLOW,
      technicalAssessment: assessmentOptions.RED,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.YELLOW,
      comments: "Comment14",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],

  PA9: [
    {
      id: 17,
      name: "Program 9",
      sector: "Airborne Combat Systems",
      division: "Agile Development Group",
      tier: 1,
      contractType: "Type 1",
      contractValue: 1050700,
      contractNumber: "193847",
      contractStartDate: "07/25/2024",
      contractEndDate: "07/24/2029",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase9",
      site: "City9/State9",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement9",
      budgetedCostWorkScheduledCumulative: 1800,
      budgetedCostWorkPerformedCumulative: 2800,
      actualCostWorkPerformedCumulative: 2300,
      budgetAtComplete: 3800,
      estimateAtComplete: 3300,
      estimateToComplete: 1300,
      managementReserve: 700,
      weightedRisksAndOpportunities: 600,
      schedulePerformanceIndexCumulative: 1.1,
      costPerformanceIndexCumulative: 1.08,
      customerAssessment: assessmentOptions.GREEN,
      technicalAssessment: assessmentOptions.BLUE,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.GREEN,
      comments: "Comment15",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 18,
      name: "Program 9",
      sector: "Airborne Combat Systems",
      division: "Agile Development Group",
      tier: 1,
      contractType: "Type 1",
      contractValue: 1050700,
      contractNumber: "193847",
      contractStartDate: "07/25/2024",
      contractEndDate: "07/24/2029",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase9",
      site: "City9/State9",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: false,
      earnedValueManagementSystemReportingRequirement: "Requirement9",
      budgetedCostWorkScheduledCumulative: 1850,
      budgetedCostWorkPerformedCumulative: 2850,
      actualCostWorkPerformedCumulative: 2350,
      budgetAtComplete: 3850,
      estimateAtComplete: 3350,
      estimateToComplete: 1350,
      managementReserve: 750,
      weightedRisksAndOpportunities: 650,
      schedulePerformanceIndexCumulative: 1.12,
      costPerformanceIndexCumulative: 1.1,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.BLUE,
      riskAssessment: assessmentOptions.YELLOW,
      overallProgram: assessmentOptions.GREEN,
      comments: "Comment16",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],

  PA10: [
    {
      id: 19,
      name: "Program 10",
      sector: "Airborne Combat Sytems",
      division: "RSAT",
      tier: 1,
      contractType: "Type 3",
      contractValue: 910320,
      contractNumber: "658293",
      contractStartDate: "08/30/2024",
      contractEndDate: "8/29/2030",
      reportingPeriod: 202509,
      teamMembers: [],
      programPhase: "Phase10",
      site: "City10/State10",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement10",
      budgetedCostWorkScheduledCumulative: 1900,
      budgetedCostWorkPerformedCumulative: 2900,
      actualCostWorkPerformedCumulative: 2400,
      budgetAtComplete: 3900,
      estimateAtComplete: 3400,
      estimateToComplete: 1400,
      managementReserve: 800,
      weightedRisksAndOpportunities: 700,
      schedulePerformanceIndexCumulative: 1.03,
      costPerformanceIndexCumulative: 1.05,
      customerAssessment: assessmentOptions.YELLOW,
      technicalAssessment: assessmentOptions.YELLOW,
      riskAssessment: assessmentOptions.BLUE,
      overallProgram: assessmentOptions.GREEN,
      comments: "Comment17",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
    {
      id: 20,
      name: "Program 10",
      sector: "Airborne Combat Sytems",
      division: "RSAT",
      tier: 1,
      contractType: "Type 3",
      contractValue: 910320,
      contractNumber: "658293",
      contractStartDate: "08/30/2024",
      contractEndDate: "8/29/2030",
      reportingPeriod: 202508,
      teamMembers: [],
      programPhase: "Phase10",
      site: "City10/State10",
      defenseFinancialAcquisitionRegulationClause: true,
      costAndSoftwareDataReportingSystemClause: true,
      earnedValueManagementSystemReportingRequirement: "Requirement10",
      budgetedCostWorkScheduledCumulative: 1950,
      budgetedCostWorkPerformedCumulative: 2950,
      actualCostWorkPerformedCumulative: 2450,
      budgetAtComplete: 3950,
      estimateAtComplete: 3450,
      estimateToComplete: 1450,
      managementReserve: 850,
      weightedRisksAndOpportunities: 750,
      schedulePerformanceIndexCumulative: 1.06,
      costPerformanceIndexCumulative: 1.07,
      customerAssessment: assessmentOptions.BLUE,
      technicalAssessment: assessmentOptions.GREEN,
      riskAssessment: assessmentOptions.GREEN,
      overallProgram: assessmentOptions.BLUE,
      comments: "Comment18",
      previousRevision: null,
      program: undefined,
      user: undefined,
      paNumber: "",
      created: ""
    },
  ],
};
