"""
`Program` represents an effort within
L3Harris Technologies. These efforts generate revenue for the
organization and/or advance its objectives. A `Program` consists
of several attributes, as well as metadata that may be used to
provide insights into those attributes. `Program Review tool`
uses `Program` data to generate its content for its users. This
content is primarily a set of PowerPoint slides that summarize the
health of a `Program`. `Program`s may be grouped together to form
`Portfolio`s that a `User` may quickly access so that they can
easily generate `Program Review Tool`s content. These `Program`s
will be fetched/validated from an external source (eg. FDW or AXIS).
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from portal.models import BasicInformationAbstractModel, DateTimeAbstractModel


class Program(BasicInformationAbstractModel, DateTimeAbstractModel):
    """
    `Program` represents an effort within L3Harris Technologies.
    These efforts generate revenue for the organization and/or
    advance its objectives.

    A `Program` includes:
        * id (int): An auto-generated number managed by the database.
        * pa_number (models.CharField): A unique identifier for a program
            generated by the Finance department.
        * name (models.CharField): The name of the `Program`.
        * segment (users.Segment): An organization unit of L3Harris Technologies.
        * sector (models.CharField): An organizational unit of a segment
            (eg. Space and Airborne Systems).
        * division (models.CharField): An organization unit of a sector
            (eg. Space Systems).
        * tier (models.PositiveSmallIntegerField): Describes the mission importance
            and risk of a `Program`. Limited to the range of 1-4, where 1 is
            considered the highest tier.
        * contract_value (models.PositiveBigIntegerField): The dollar value assigned
            to the `Program`.
        * active_status (models.BooleanField): Whether the `Program` is active.
        * created (models.DateTimeField): The date & time this `Program` was created.
        * modified (models.DateTimeField): The date & time this `Program` was last modified.
    """

    pa_number = models.CharField(max_length=64, unique=True)
    segment = models.ForeignKey("users.Segment", on_delete=models.SET_NULL, null=True)
    sector = models.CharField(max_length=1028)
    division = models.CharField(max_length=1028)
    tier = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)]
    )
    contract_value = models.PositiveBigIntegerField()
    active_status = models.BooleanField(null=True, default=None)

    # Removed fields from superclass.
    description = None  # type: ignore[assignment]

    def __str__(self) -> str:
        """String Representation of a `Program`."""

        return f"Program(id={self.id}, pa_number={self.pa_number}, name={self.name})"

    @property
    def id(self) -> int:
        """Primary Key."""

        return self.id

    class Meta:
        """Meta Class for `Program`."""

        db_table_comment = ""
        default_related_name = "programs"
        indexes = [
            models.Index(fields=("pa_number",), name="program_pa_number"),
            models.Index(fields=("name",), name="program_name"),
            models.Index(fields=("id",), name="program_id"),
        ]
        verbose_name = "program"
        verbose_name_plural = "programs"
