"""
`Program` represents an effort within
L3Harris Technologies. These efforts generate revenue for the
organization and/or advance its objectives. A `Program` consists
of several attributes, as well as metadata that may be used to
provide insights into those attributes. `Program Review tool`
uses `Program` data to generate its content for its users. This
content is primarily a set of PowerPoint slides that summarize the
health of a `Program`. `Program`s may be grouped together to form
`Portfolio`s that a `User` may quickly access so that they can
easily generate `Program Review Tool`s content. These `Program`s
will be fetched/validated from an external source (eg. FDW or AXIS).
"""

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from portal.models import BasicInformationAbstractModel, DateTimeAbstractModel


class Program(BasicInformationAbstractModel, DateTimeAbstractModel):
    """
    `Program` represents an effort within L3Harris Technologies.
    These efforts generate revenue for the organization and/or
    advance its objectives.

    A `Program` includes:
        * id (int): An auto-generated number managed by the database.
        * pa_number (models.CharField): A unique identifier for a program
            generated by the Finance department.
        * name (models.CharField): The name of the `Program`.
        * segment (users.Segment): An organization unit of L3Harris Technologies.
        * sector (models.CharField): An organizational unit of a segment
            (eg. Space and Airborne Systems).
        * division (models.CharField): An organization unit of a sector
            (eg. Space Systems).
        * tier (models.PositiveSmallIntegerField): Describes the mission importance
            and risk of a `Program`. Limited to the range of 1-4, where 1 is
            considered the highest tier.
        * contract_type (models.CharField): The classification of the
            contract (e.g., FFP, CPFF, T&M) that defines terms of pricing,
            risk, and reimbursement.
        * contract_number (models.CharField): The unique identifier assigned
            to a contractual agreement between the customer and L3Harris
            technologies.
        * contract_value (models.PositiveBigIntegerField): The dollar value
            assigned to the `Program`.
        * contract_start_date (models.DateField): The date on which the contractual
            period of performance officially begins.
        * contract_end_date (models.DateField): The date on which the contractual period of
            performance is scheduled to conclude.
        * actual_cost_work_performed_cumulative (models.DecimalField): The total actual cost
            incurred for all completed work up to the reporting period.
        * budgeted_cost_work_performed_cumulative (models.DecimalField): The cumulative value
            of the budgeted cost for completed work as of the reporting period.
        * budgeted_cost_work_scheduled_cumulative (models.DecimalField): The cumulative value
            of the budgeted cost for work that was scheduled to be completed by the
            reporting period.
        * cost_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ ACWP) that
            measures cost efficiency in executing the `Program`.
        * schedule_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ BCWS)
            that measures schedule efficiency in completing the planned work.
        * budget_at_complete (models.DecimalField): The total budgeted cost for the
            entire scope of work as defined in the baseline plan.
        * estimate_at_complete (models.DecimalField): The current forecast of the total
            expected cost required to complete the `Program`.
        * estimate_to_complete (models.DecimalField): The projected additional cost needed
            to complete the remaining `Program` work (EAC - ACWP).
        * management_reserve (models.DecimalField): A budget set aside by management to cover
            unforeseen risks or changes outside the scope of baseline work.
        * weighted_risks_and_opportunities (models.DecimalField): The net financial impact of
            risks and opportunities, weighted by their probability of occurrence.
        * active_status (models.BooleanField): Whether the `Program` is active.
        * created (models.DateTimeField): The date & time this `Program` was created.
        * modified (models.DateTimeField): The date & time this `Program` was last modified.
    """

    pa_number = models.CharField(max_length=64, unique=True)
    segment = models.ForeignKey("users.Segment", on_delete=models.SET_NULL, null=True)
    sector = models.CharField(max_length=1028, default="")
    division = models.CharField(max_length=1028, default="")
    tier = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)], null=True
    )
    contract_type = models.CharField(max_length=64, default="")
    contract_number = models.CharField(max_length=32, default="")
    contract_value = models.PositiveBigIntegerField(null=True)
    contract_start_date = models.DateField(null=True, default=None)
    contract_end_date = models.DateField(null=True, default=None)
    actual_cost_work_performed_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    budgeted_cost_work_performed_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    budgeted_cost_work_scheduled_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    cost_performance_index_cumulative = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, default=None
    )
    schedule_performance_index_cumulative = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, default=None
    )
    budget_at_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    estimate_at_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    estimate_to_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    management_reserve = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    weighted_risks_and_opportunities = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    active_status = models.BooleanField(null=True, default=None)

    # Removed fields from superclass.
    description = None  # type: ignore[assignment]

    def __str__(self) -> str:
        """String Representation of a `Program`."""

        return f"Program(id={self.id}, pa_number={self.pa_number}, name={self.name})"

    @property
    def id(self) -> int:
        """Primary Key."""

        return self.id

    class Meta:
        """Meta Class for `Program`."""

        db_table_comment = ""
        default_related_name = "programs"
        indexes = [
            models.Index(fields=("pa_number",), name="program_pa_number"),
            models.Index(fields=("name",), name="program_name"),
            models.Index(fields=("id",), name="program_id"),
        ]
        verbose_name = "program"
        verbose_name_plural = "programs"
