# Generated by Django 5.0.2 on 2024-08-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("search_term", models.CharField(max_length=512)),
                (
                    "resources",
                    models.ManyToManyField(
                        db_table="query_resources", to="directory.resource"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "query",
                "verbose_name_plural": "queries",
                "db_table_comment": (
                    """
                    `Query` represents a search for a `Resource` by a `User`.
                    `Query` provides analytical data for resources so that
                    `BI Portal` may provide insights and improve the user's
                    experience.

                    A `Query` includes:
                        * id (int): An auto-generated number managed by the database.
                        * user (contrib.auth.models.User): A `BI Portal` user.
                        * search_term (models.CharField): A search string submitted by the user.
                        * resources (models.ManyToManyField[directory.models.Resource]): A set
                            of resources fetched with this query at the time it was created.
                        * created (models.DateTimeField): The date & time this `Query` was created.
                    """
                ),
                "ordering": ["search_term", "-created"],
                "default_related_name": "queries",
                "indexes": [
                    models.Index(fields=["search_term"], name="query_search_term"),
                    models.Index(fields=["user"], name="query_user"),
                    models.Index(fields=["id"], name="query_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="directory.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "visit",
                "verbose_name_plural": "visits",
                "db_table_comment": (
                    """
                    `Visit` represents a visit (click) to a `Resource`.
                    `Visit` provides analytical data for resources so that
                    `BI Portal` may provide insights and improve the user's
                    experience.

                    A `Visit` includes:
                        * id (int): An auto-generated number managed by the database.
                        * user (contrib.auth.models.User): A `BI Portal` user.
                        * resource (directory.models.Resource): A visited `Resource`.
                        * created (models.DateTimeField): The date & time this `Visit` was created.
                    """
                ),
                "ordering": ["-created"],
                "default_related_name": "visits",
                "indexes": [
                    models.Index(fields=["resource"], name="visit_resource"),
                    models.Index(fields=["user"], name="visit_user"),
                    models.Index(fields=["id"], name="visit_id"),
                ],
            },
        ),
    ]
