# Generated by Django 5.0.2 on 2024-08-26 14:06

import directory.models.Resource
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("level", models.PositiveIntegerField(editable=False, unique=True)),
            ],
            options={
                "verbose_name": "employee level",
                "verbose_name_plural": "employee levels",
                "db_table_comment": (
                    """
                    `EmployeeLevel` represents a hierarchical level of leadership within
                    the organization and a level of concern for a resource. Employee Levels
                    help to classify a resource, and provide metadata. Employee Levels are
                    a strictly defined set created by a superuser.

                    An `EmployeeLevel` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): The name of the `EmployeeLevel`.
                        * description (models.CharField): A short/detailed description of what
                            this `EmployeeLevel` is.
                        * level (models.PositiveIntegerField): An immutable numerical representation
                            of an `EmployeeLevel`.
                        * created (models.DateTimeField): The date & time this `EmployeeLevel` was
                            created.
                        * modified (models.DateTimeField): The date & time this `EmployeeLevel` was last
                            modified.
                    """
                ),
                "ordering": ["level"],
                "default_related_name": "employeelevels",
                "indexes": [
                    models.Index(fields=["level"], name="employeelevel_level"),
                    models.Index(fields=["name"], name="employeelevel_name"),
                    models.Index(fields=["id"], name="employeelevel_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "function",
                "verbose_name_plural": "functions",
                "db_table_comment": (
                    """
                    `Function` represents a primary organizational unit that encompasses
                    a broad area of expertise and responsibility within the organization.
                    Functions help to classify a resource, and provide metadata. Functions
                    are a strictly defined set created by a superuser.

                    A `Function` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): The name of the `Function`.
                        * description (models.CharField): A short/detailed description of what
                            this `Function` is.
                        * created (models.DateTimeField): The date & time this `Function` was created.
                        * modified (models.DateTimeField): The date & time this `Function` was last
                            modified.
                    """
                ),
                "ordering": ["name"],
                "default_related_name": "functions",
                "indexes": [
                    models.Index(fields=["name"], name="function_name"),
                    models.Index(fields=["id"], name="function_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="directory.function",
                    ),
                ),
            ],
            options={
                "verbose_name": "subfunction",
                "verbose_name_plural": "subfunctions",
                "db_table_comment": (
                    """
                    `SubFunction` represents a specialized division within a `Function`
                    that focuses on a more specific area of expertise. SubFunctions help
                    to classify a resource, and provide metadata. SubFunctions are a strictly
                    defined set created by a superuser.

                    A `SubFunction` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): The name of the `SubFunction`.
                        * description (models.CharField): A short/detailed description of what
                            this `SubFunction` is.
                        * function (directory.models.Function): The `Function` that this `SubFunction`
                            relates to.
                        * created (models.DateTimeField): The date & time this `SubFunction` was created.
                        * modified (models.DateTimeField): The date & time this `SubFunction` was last
                            modified.
                    """
                ),
                "ordering": ["name"],
                "default_related_name": "subfunctions",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=1028, unique=True)),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "db_table_comment": (
                    """
                    `Tag` represents a keyword, used to classify a resource.
                    Tags consist primary of an arbitrary label, created by
                    a superuser. Tags provide metadata and additional insight
                    about a resource.

                    A `Tag` includes:
                        * id (int): An auto-generated number managed by the database.
                        * label (models.CharField): An arbitrary keyword, created by a superuser.
                        * created (models.DateTimeField): The date & time this `Tag` was created.
                        * modified (models.DateTimeField): The date & time this `Tag` was last modified.
                    """
                ),
                "ordering": ["label"],
                "default_related_name": "tags",
                "indexes": [
                    models.Index(fields=["label"], name="tag_label"),
                    models.Index(fields=["id"], name="tag_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("uid", models.UUIDField(default=uuid.uuid4)),
                ("revision_number", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=512)),
                ("url", models.URLField()),
                (
                    "thumbnail",
                    models.ImageField(
                        null=True,
                        upload_to=directory.models.thumbnail_path,
                    ),
                ),
                ("type", models.CharField(max_length=512)),
                ("download", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                (
                    "employee_levels",
                    models.ManyToManyField(
                        db_table="directory_resource_employeelevels",
                        to="directory.employeelevel",
                    ),
                ),
                (
                    "previous_revision",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="directory.resource",
                    ),
                ),
                (
                    "subfunctions",
                    models.ManyToManyField(
                        db_table="directory_resource_subfunctions",
                        to="directory.subfunction",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        db_table="directory_resource_tags", to="directory.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
                "db_table_comment": (
                    """
                    `Resource` represents a link to an internal tool within L3Harris
                    Technologies. Resources act as a point of access for those internal
                    tools, thus allowing `BI Portal` to function as a web directory.
                    Resources serve as the primary content of the `BI Portal`.

                    A `Resource` includes:
                        * id (int): An auto-generated number managed by the database.
                        * uid (models.UUIDField): A shared id for all revisions of the same resource.
                        * previous_revision (directory.models.Resource): A reference to its previous
                            revision.
                        * revision_number (models.PositiveIntegerField): A number that
                            uniquely identifies a resource amongst its revisions.
                        * name (models.CharField): The name of the `Resource`.
                        * description (models.CharField): A short/detailed description of what
                            this `Resource` is.
                        * url (models.URLField): The web address of a resource.
                        * thumbnail (models.ImageField): An icon to display as a thumbnail for the
                            resource.
                        * employee_levels (models.ManyToManyField[directory.models.EmployeeLevel]): 
                            A set of `EmployeeLevel`s that relate to this `Resource`. EmployeeLevel
                            helps to classify a resource, and provide metadata.
                        * subfunctions (models.ManyToManyField[directory.models.SubFunction]) A set
                            of `SubFunction`s that relate to this `Resource`. SubFunction helps to
                            classify a resource, and provide metadata.
                        * tags (models.ManyToManyField[directory.models.Tag]) A set of `Tag`s that
                            relate to this `Resource`. Tag helps to classify a resource, and
                            provide metadata.
                        * type (models.CharField): A source for a `Resource`. Where the content may be
                            stored.
                        * download (models.BooleanField): Whether this `Resource` provides downloadable
                            content.
                        * active (model.BooleanField): Whether this `Resource` is available to the user.
                        * created (models.DateTimeField): The date & time this `Resource` was created.
                    """
                ),
                "ordering": ["name", "-created"],
                "default_related_name": "resources",
            },
        ),
        migrations.AddIndex(
            model_name="subfunction",
            index=models.Index(fields=["function"], name="subfunction_function"),
        ),
        migrations.AddIndex(
            model_name="subfunction",
            index=models.Index(fields=["name"], name="subfunction_name"),
        ),
        migrations.AddIndex(
            model_name="subfunction",
            index=models.Index(fields=["id"], name="subfunction_id"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["uid", "revision_number"], name="resource_revision"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["name"], name="resource_name"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["id"], name="resource_id"),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("uid", "revision_number"), name="resource_revision_id"
            ),
        ),
    ]
