# Generated by Django 5.0.2 on 2025-02-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="url",
            field=models.URLField(max_length=1024),
        ),
    ]
