# Generated by Django 5.0.2 on 2025-02-20 20:07

import directory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_resource_url_increase_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="revision_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="thumbnail",
            field=models.ImageField(
                max_length=512,
                null=True,
                upload_to=directory.models.thumbnail_path,
            ),
        ),
    ]
