# Generated by Django 5.0.2 on 2025-05-29 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_modify_thumbnail_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PointOfContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.BooleanField(default=None, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="directory.resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "point of contact",
                "verbose_name_plural": "point of contacts",
                "default_related_name": "pointofcontacts",
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="point_of_contacts",
            field=models.ManyToManyField(
                through="directory.PointOfContact", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="pointofcontact",
            constraint=models.UniqueConstraint(
                fields=("resource", "contact"), name="resource_contact_id"
            ),
        ),
    ]
