# Generated by Django 5.0.2 on 2025-05-29 13:44

import logging
from typing import cast

from django.db import migrations

from directory import models as DirectoryModels
from request import models as RequestModels


def add_primary_point_of_contact_to_resources(apps, schema_editor):
    """For all existing `Resource` records, create a related
    `PointOfContact` record that designates the originator
    of the `Resource`'s `Request` as the primary point of
    contact."""

    LOGGER = logging.getLogger(__name__)

    Resource = cast(DirectoryModels.Resource, apps.get_model("directory", "Resource"))

    LOGGER.info(
        "Updating existing Resources with an appropriate primary PointOfContact..."
    )

    for record in Resource.objects.all():
        request = cast(RequestModels.Request, record.requests)
        originator = request.originator.user
        record.point_of_contacts.add(originator, through_defaults={"primary": True})

    row_count = Resource.objects.count()
    log_msg = f"Updated {row_count} Resource records..."
    LOGGER.info(log_msg)


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0004_add_point_of_contact_model"),
    ]

    operations = [migrations.RunPython(add_primary_point_of_contact_to_resources)]
