# Generated by Django 5.0.2 on 2025-06-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0005_add_primary_point_of_contacts_to_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
