# Generated by Django 5.0.2 on 2025-07-28 12:59

import logging
import pandas as pd
from typing import cast

from django.db import migrations

from directory import models as DirectoryModels


def update_tag_labels(apps, _):
    """Update label of each tag to match its source within `master.xlsx`."""

    LOGGER = logging.getLogger(__name__)

    Tag = cast(DirectoryModels.Tag, apps.get_model("directory", "Tag"))

    df = pd.read_excel(
        "portal/db/init/scripts/source/master.xlsx", sheet_name="CURATED"
    )

    LOGGER.info("Reading Tag Labels...")

    # Read normal tags from master source file.
    df_tags = df.dropna(subset=["Tags"])

    LOGGER.info("Updating Tag Labels...")

    # Create de-duped list of normal tags from master source file.
    tags = set()
    for tag in df_tags["Tags"]:
        labels = [label.strip() for label in tag.split(",")]
        labels = [label for label in labels if len(label)]
        tags |= set(labels)
    tags = list(tags)

    # Update tag labels to match those in the master source file.
    for tag in tags:
        Tag.objects.filter(label__iexact=tag).update(label=tag)

    LOGGER.info("Reading Site Labels...")

    # Read site tags from master source file.
    df_sites = df.dropna(subset=["Site"])

    LOGGER.info("Updating Site Labels...")

    # Create a de-duped list of site tags from the master source file.
    sites = set()
    for tag in df_sites["Site"]:
        sites.add(tag)
    sites = list(sites)

    # Update site labels to match those in the master source file.
    for tag in sites:
        Tag.objects.filter(label__iexact=f"filter::site:{tag}").update(
            label=f"filter::site:{tag}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0006_add_disabled_field_to_resources"),
    ]

    operations = [migrations.RunPython(update_tag_labels)]
