"""
Arguments to be shared for Portfolio's fetch
controller pytests.
"""

FETCH_PORTFOLIO_USER_EMAIL: str = "May.Parker@harris.com"

FETCH_PORTFOLIO_USER_EMAIL_PERMISSIONS_DENIED: str = "Peter.Parker@harris.com"

FETCH_PORTFOLIOS_EXPECTED_PORTFOLIOS_COUNT = 2

FETCH_PORTFOLIOS_EXPECTED_PORTFOLIOS = [
    {
        "id": 1,
        "name": "Portfolio Name 1",
        "user": {
            "id": 1,
            "username": "May.Parker@harris.com",
            "email": "May.Parker@l3harris.com",
            "first_name": "May",
            "last_name": "Parker",
            "is_active": True,
        },
        "programs": [
            {
                "id": 1,
                "segment": "SPACE & AIRBORNE SYSTEMS",
                "name": "SOA IDIQ II_6C27",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "pa_number": "6C27",
                "sector": "Airborne Combat Systems",
                "division": "Electronic Warfare",
                "tier": 1,
                "contract_type": "FFP",
                "contract_number": "CN865247",
                "contract_value": 3000000000,
                "contract_start_date": "2025-01-01",
                "contract_end_date": "2025-12-01",
                "actual_cost_work_performed_cumulative": 70.36,
                "budgeted_cost_work_performed_cumulative": 20.55,
                "budgeted_cost_work_scheduled_cumulative": 59.46,
                "cost_performance_index_cumulative": 0.51,
                "schedule_performance_index_cumulative": 1.25,
                "budget_at_complete": 41.97,
                "estimate_at_complete": 84.95,
                "estimate_to_complete": 36.02,
                "management_reserve": 47.9,
                "weighted_risks_and_opportunities": 30.27,
                "active_status": True,
                "is_manual_metrics_entry": False,
                "team_members": [],
            },
            {
                "id": 2,
                "segment": "SPACE & AIRBORNE SYSTEMS",
                "name": "Zeus CLIN 0005 Single Launch_10LR",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "pa_number": "10LR",
                "sector": "Space Systems",
                "division": "Surveillance Systems",
                "tier": 3,
                "contract_type": "FFP",
                "contract_number": "CN323301",
                "contract_value": 3000000000,
                "contract_start_date": "2025-01-01",
                "contract_end_date": "2025-12-01",
                "actual_cost_work_performed_cumulative": 77.02,
                "budgeted_cost_work_performed_cumulative": 52.81,
                "budgeted_cost_work_scheduled_cumulative": 53.5,
                "cost_performance_index_cumulative": 1.18,
                "schedule_performance_index_cumulative": 1.68,
                "budget_at_complete": 46.33,
                "estimate_at_complete": 98.95,
                "estimate_to_complete": 54.6,
                "management_reserve": 29.55,
                "weighted_risks_and_opportunities": 72.65,
                "active_status": True,
                "is_manual_metrics_entry": False,
                "team_members": [],
            },
        ],
        "created": "2024-08-27T12:00:00-04:00",
        "modified": "2024-08-27T12:00:00-04:00",
    },
    {
        "id": 2,
        "name": "Portfolio Name 2",
        "user": {
            "id": 1,
            "username": "May.Parker@harris.com",
            "email": "May.Parker@l3harris.com",
            "first_name": "May",
            "last_name": "Parker",
            "is_active": True,
        },
        "programs": [
            {
                "id": 3,
                "segment": "SPACE & AIRBORNE SYSTEMS",
                "name": "Zeus CLIN 0006 Demo and Ops_10MR",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "pa_number": "10MR",
                "sector": "Space Systems",
                "division": "Surveillance Systems",
                "tier": 4,
                "contract_type": "FFP",
                "contract_number": "CN128460",
                "contract_value": 3000000000,
                "contract_start_date": "2025-01-01",
                "contract_end_date": "2025-12-01",
                "actual_cost_work_performed_cumulative": 88.79,
                "budgeted_cost_work_performed_cumulative": 46.65,
                "budgeted_cost_work_scheduled_cumulative": 17.16,
                "cost_performance_index_cumulative": 1.94,
                "schedule_performance_index_cumulative": 0.02,
                "budget_at_complete": 20.44,
                "estimate_at_complete": 17.14,
                "estimate_to_complete": 70.89,
                "management_reserve": 88.7,
                "weighted_risks_and_opportunities": 12.17,
                "active_status": True,
                "is_manual_metrics_entry": False,
                "team_members": [],
            },
            {
                "id": 4,
                "segment": "SPACE & AIRBORNE SYSTEMS",
                "name": "Zeus Critical Spares_61GK",
                "created": "2024-08-27T12:00:00-04:00",
                "modified": "2024-08-27T12:00:00-04:00",
                "pa_number": "61GK",
                "sector": "Space Systems",
                "division": "Surveillance Systems",
                "tier": 4,
                "contract_type": "FFP",
                "contract_number": "CN854674",
                "contract_value": 3000000000,
                "contract_start_date": "2025-01-01",
                "contract_end_date": "2025-12-01",
                "actual_cost_work_performed_cumulative": 48.58,
                "budgeted_cost_work_performed_cumulative": 18.72,
                "budgeted_cost_work_scheduled_cumulative": 75.86,
                "cost_performance_index_cumulative": 0.46,
                "schedule_performance_index_cumulative": 0.79,
                "budget_at_complete": 63.24,
                "estimate_at_complete": 74.26,
                "estimate_to_complete": 84.57,
                "management_reserve": 40.63,
                "weighted_risks_and_opportunities": 38.8,
                "active_status": True,
                "is_manual_metrics_entry": False,
                "team_members": [],
            },
        ],
        "created": "2024-08-27T12:00:00-04:00",
        "modified": "2024-08-27T12:00:00-04:00",
    },
]
