# Generated by Django 5.0.2 on 2024-08-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("directory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryFilterState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "employee_levels",
                    models.ManyToManyField(
                        db_table="preferences_queryfilterstate_employeelevels",
                        to="directory.employeelevel",
                    ),
                ),
                (
                    "functions",
                    models.ManyToManyField(
                        db_table="preferences_queryfilterstate_functions",
                        to="directory.function",
                    ),
                ),
                (
                    "search",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.query",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        db_table="preferences_queryfilterstate_tags", to="directory.tag"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "queryfilterstate",
                "verbose_name_plural": "queryfilterstates",
                "db_table_comment": (
                    """
                    `QueryFilterState` represents the stored filtered UI state
                    for a user. This database table will store at most, 1
                    `QueryFilterState` per user. Once a `QueryFilterState` is
                    instantiated for a user it should never be deleted, but only
                    modified, unless that user is deleted.

                    A `QueryFilterState` includes:
                        * id (int): An auto-generated number managed by the database.
                        * search (analytics.models.Query): A search query made by the user.
                        * user (contrib.auth.models.User): `User` that is related to the stored
                            filtered state.
                        * functions (models.ManyToManyField[directory.models.Function]): `Function`s
                            selected by the user.
                        * employee_levels (models.ManyToManyField[directory.models.EmployeeLevel]):
                            `EmployeeLevel`s selected by the user.
                        * tags (models.ManyToManyField[directory.models.Tag]): `Tag`s for resources
                            selected by the user.
                        * created (models.DateTimeField): The date & time this `QueryFilterState`
                            was created.
                        * modified (models.DateTimeField): The date & time this `QueryFilterState`
                            was last modified.
                    """
                ),
                "ordering": ["id"],
                "default_related_name": "queryfilterstates",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("rank", models.PositiveIntegerField()),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="directory.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "favorite",
                "verbose_name_plural": "favorites",
                "db_table_comment": (
                    """
                    `Favorite` represents a resource favorited by a user.
                    A `Favorite` allows a user to quickly access a resource
                    through the UI.

                    A `Favorite` includes:
                        * id (int): An auto-generated number managed by the database.
                        * user (contrib.auth.models.User): `User` that has favorited the related
                            `Resource`.
                        * resource (directory.models.Resource): `Resource` that is being favorited
                            by the user.
                        * rank (models.PositiveIntegerField): A whole number indicating the
                            order of this `Favorite` amongst other favorited resources for the
                            related `User`.
                        * created (models.DateTimeField): The date & time this `Favorite`
                            was created.
                    """
                ),
                "ordering": ["rank", "-created"],
                "default_related_name": "favorites",
                "indexes": [
                    models.Index(fields=["resource"], name="favorite_resource"),
                    models.Index(fields=["user"], name="favorite_user"),
                    models.Index(fields=["id"], name="favorite_id"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "resource"), name="favorite_resource_for_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "rank"), name="rank_for_user_favorite"
            ),
        ),
        migrations.AddIndex(
            model_name="queryfilterstate",
            index=models.Index(fields=["user"], name="queryfilterstate_user"),
        ),
        migrations.AddIndex(
            model_name="queryfilterstate",
            index=models.Index(fields=["id"], name="queryfilterstate_id"),
        ),
    ]
