x-logging-settings: &logging-settings
    logging:
        driver: "json-file"
        options:
            max-size: "256k"
            max-file: "3"

services:
    database:
        image: postgres:16.3-bullseye
        restart: unless-stopped
        container_name: ${APP_NAME}-db-${USER}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_PROGRAM_REVIEW_TOOL_NAME: ${POSTGRES_PROGRAM_REVIEW_TOOL_NAME}
            POSTGRES_PROGRAM_REVIEW_TOOL_USER: ${POSTGRES_PROGRAM_REVIEW_TOOL_USER}
            POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD: ${POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD}
            FDW_DATABASE_NAME: ${FDW_DATABASE_NAME}
            FDW_DATABASE_USER: ${FDW_DATABASE_USER}
            FDW_DATABASE_PASSWORD: ${FDW_DATABASE_PASSWORD}
            FDW_DATABASE_HOST: ${FDW_DATABASE_HOST}
            FDW_DATABASE_PORT: ${FDW_DATABASE_PORT}
            AXIS_DATABASE_NAME: ${AXIS_DATABASE_NAME}
            AXIS_DATABASE_USER: ${AXIS_DATABASE_USER}
            AXIS_DATABASE_PASSWORD: ${AXIS_DATABASE_PASSWORD}
            AXIS_DATABASE_HOST: ${AXIS_DATABASE_HOST}
            AXIS_DATABASE_PORT: ${AXIS_DATABASE_PORT}
        <<: *logging-settings
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/db/init:/docker-entrypoint-initdb.d
