"""
`Task` represents a step in a plan for a program to return to green. 
Each `Task` created by a `Program_Member` is stored within our `Task` model.
Progress of a `Task` is tracked through reporting periods, with a `Task`s 
status finalized at the end of the period so a history can be traced.
A program's `Task`s are pulled with the most current `Record` in a reporting period,
to give an overall status of a program's health and progress. 
"""

# pylint: disable=no-member
from django.contrib.auth import get_user_model
from django.db import models

from django.contrib.postgres.fields import ArrayField
from portal.models import BasicInformationAbstractModel


class Task(BasicInformationAbstractModel):
    """
    `Task` represents a step in a plan for a program to return to green.
    Each `Task` created by a `Program_Member` is stored within our `Task` model.
    Progress of a `Task` is tracked through reporting periods, with a `Task`s
    status finalized at the end of the period so a history can be traced.
    A program's `Task`s are pulled with the most current `Record` in a reporting period,
    to give an overall status of a program's health and progress.

    A `Task` includes:
        * id (int): An auto-generated number managed by the database.
        * previous_revision (directory.models.Task): A reference to its previous
            revision.
        * program (models.ForeignKey): The associated `Program`.
        * reporting_period (Array[models.IntegerField]): The reporting periods (e.g., `202306` for June 2023)
            where the task exists and has remained unchanged.
        * pa_number (models.CharField): A unique identifier for a program
            generated by the Finance department.
        * order (models.IntegerField): The order in which this task should appear.
        * name (models.CharField): The name of the task.
        * description (models.CharField): A description of the the task.
        * owner (auth.User): A `User` who is in charge of seeing the task completed,
            does not have to be a `Program_Member`.
        * status (models.CharField): A description of the current state of the task.
        * create_date (models.DateField): The date this `Task` was originally created.
        * target_date (models.DateField): The date this `Task` should be completed by.
        * complete_date (models.DateField): The date this `Task` has been completed by.
        * archive_date (models.DateField): The date this `Task` has been archived.
    """

    previous_revision: models.OneToOneField = models.OneToOneField(
        "self", null=True, on_delete=models.SET_NULL
    )
    program = models.ForeignKey("program_review_tool.Program", on_delete=models.CASCADE)
    pa_number = models.CharField(max_length=64, unique=True)
    reporting_period = ArrayField(
        base_field=models.IntegerField(), size=None, null=True, default=list
    )
    order = models.IntegerField(null=True)
    owner = models.ForeignKey(
        get_user_model(), to_field="username", on_delete=models.SET_NULL, null=True
    )
    status: models.CharField = models.CharField(max_length=512)
    create_date = models.DateField()
    target_date = models.DateField()
    complete_date = models.DateField(null=True, default=None)
    archive_date = models.DateField(null=True, default=None)

    def __str__(self) -> str:
        """String Representation of `Task`."""
        return (
            f"Task(id={self.id}, pa_number={self.pa_number},"
            f" order={self.order}, name={self.name}, description={self.description},"
            f" create_date={self.create_date}, target_date={self.target_date}, complete_date={self.complete_date},"
            f" status={self.status}, reporting_period={self.reporting_period})"
        )

    @property
    def id(self) -> int:
        """Primary Key."""
        return self.id

    class Meta:
        """Meta class for `Task`."""

        db_table_comment = (
            "`Task` represents a step in a plan for a program to return to green. "
            "Each `Task` created by a `Program_Member` is stored within our `Task` model. "
            "Progress of a `Task` is tracked through reporting periods, with a `Task`s "
            "status finalized at the end of the period so a history can be traced. "
            "A program's `Task`s are pulled with the most current `Record` in a reporting period, "
            "to give an overall status of a program's health and progress."
            "A `Task` includes:"
            "    * id (int): An auto-generated number managed by the database."
            "    * previous_revision (directory.models.Task): A reference to its previous"
            "        revision."
            "    * program (models.ForeignKey): The associated `Program`."
            "    * reporting_period (Array[models.IntegerField]): The reporting periods (e.g., `202306` for June 2023)"
            "        where the task exists and has remained unchanged."
            "    * pa_number (models.CharField): A unique identifier for a program"
            "        generated by the Finance department."
            "    * order (models.IntegerField): The order in which this task should appear."
            "    * name (models.CharField): The name of the task."
            "    * description (models.CharField): A description of the the task."
            "    * owner (auth.User): A `User` who is in charge of seeing the task completed,"
            "        does not have to be a `Program_Member`."
            "    * status (models.CharField): A description of the current state of the task."
            "    * create_date (models.DateField): The date this `Task` was originally created."
            "    * target_date (models.DateField): The date this `Task` should be completed by."
            "    * complete_date (models.DateField): The date this `Task` has been completed by."
            "    * archive_date (models.DateField): The date this `Task` has been archived."
        )
        default_related_name = "tasks"
        indexes = [
            models.Index(fields=("pa_number",), name="task_pa_number"),
            models.Index(fields=("id",), name="task_id"),
            models.Index(fields=("reporting_period",), name="task_reporting_periods"),
        ]
        ordering = ["-order", "-archive_date"]
        verbose_name = "task"
        verbose_name_plural = "tasks"


Task.Meta.db_table_comment = Task.__doc__  # type: ignore[assignment]
