"""
`Record` represents a Program's health and financials in a monthly snapshot, captured
through the `Program Performance Review (PPR)` Tool. These snapshots encompass both the subjective
analysis provided by a `Program Manager` or `Program Financial Analyst` and numerous metrics that 
detail the health of the `Program`. Each `Record` includes a variety of attributes, such as 
financial performance, technical assessment, risk assessment, and other key indicators of program 
health. The PPR Tool leverages `Record` data to generate comprehensive reports, primarily in the 
form of PowerBI Dashboards, that summarize the state and progress of a `Program` over time. These 
reports provide valuable insights for stakeholders, enabling them to track the evolution of a 
`Program` and make informed decisions based on historical performance and trends. Like `Program`s, 
`Record`s are fetched and validated from external sources (e.g., FDW or AXIS) to ensure accuracy 
and consistency. By maintaining a detailed log of `Record`, users can gain a holistic view of a 
`Program`'s health and effectively manage its progress. 
"""

# pylint: disable=no-member
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from portal.models import DateTimeAbstractModel


class Record(DateTimeAbstractModel):
    """
    `Record` represents a monthly snapshot of a `Program` within L3Harris Technologies.
    These efforts leverage subjective analysis and key financial metrics to track
    long-term program health.

    A `Record` includes:
        * id (int): An auto-generated number managed by the database.
        * previous_revision (directory.models.Record): A reference to its previous
            revision.
        * program (models.ForeignKey): The associated `Program`.
        * reporting_period (models.IntegerField): The reporting period (e.g., `202306` for June 2023).
        * team_members (models.ManyToManyField[program_review_tool.models.ProgramMember]):
            The team members assigned to the `Program`.
        * pa_number (models.CharField): A unique identifier for a program
            generated by the Finance department.
        * name (models.CharField): The name of the `Program`.
        * segment (users.Segment): An organizational unit of L3Harris Technologies.
        * sector (models.CharField): An organizational unit of a segment
            (eg. Space and Airborne Systems).
        * division (models.CharField): An organizational unit of a sector
            (eg. Space Systems).
        * tier (models.PositiveSmallIntegerField): Describes the mission importance
            and risk of a `Program`. Limited to the range of 1-4, where 1 is
            considered the highest tier.
        * program_phase (models.CharField): The current phase of the `Program`.
        * site (models.CharField): The L3Harris Technologies site associated with the `Program`.
        * defense_financial_acquisition_regulation_clause (models.BooleanField): Indicates whether the DFARS clause is applicable.
        * cost_and_software_data_reporting_system_clause (models.BooleanField): Indicates whether the CSDR clause is applicable.
        * earned_value_management_system_reporting_requirement (models.CharField): The EVMS reporting requirement.
        * contract_type (models.CharField): The classification of the
            contract (e.g., FFP, CPFF, T&M) that defines terms of pricing,
            risk, and reimbursement.
        * contract_number (models.CharField): The unique identifier assigned
            to a contractual agreement between the customer and L3Harris
            technologies.
        * contract_value (models.PositiveBigIntegerField): The dollar value
            assigned to the `Program`.
        * contract_start_date (models.DateField): The date on which the contractual
            period of performance officially begins.
        * contract_end_date (models.DateField): The date on which the contractual period of
            performance is scheduled to conclude.
        * actual_cost_work_performed_cumulative (models.DecimalField): The total actual cost
            incurred for all completed work up to the reporting period.
        * budgeted_cost_work_performed_cumulative (models.DecimalField): The cumulative value
            of the budgeted cost for completed work as of the reporting period.
        * budgeted_cost_work_scheduled_cumulative (models.DecimalField): The cumulative value
            of the budgeted cost for work that was scheduled to be completed by the
            reporting period.
        * cost_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ ACWP) that
            measures cost efficiency in executing the `Program`.
        * schedule_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ BCWS)
            that measures schedule efficiency in completing the planned work.
        * budget_at_complete (models.DecimalField): The total budgeted cost for the
            entire scope of work as defined in the baseline plan.
        * estimate_at_complete (models.DecimalField): The current forecast of the total
            expected cost required to complete the `Program`.
        * estimate_to_complete (models.DecimalField): The projected additional cost needed
            to complete the remaining `Program` work (EAC - ACWP).
        * management_reserve (models.DecimalField): A budget set aside by management to cover
            unforeseen risks or changes outside the scope of baseline work.
        * weighted_risks_and_opportunities (models.DecimalField): The net financial impact of
            risks and opportunities, weighted by their probability of occurrence.
        * customer_assessment (models.IntegerField): The program manager's subjective customer assessment(1-4).
        * technical_assessment (models.IntegerField): The program manager's subjective technical assessment (1-4).
        * risk_assessment (models.IntegerField): The program manager's subjective risk assessment (1-4).
        * overall_program (models.IntegerField): The program manager's subjective overall program assessment (1-4).
        * comments (models.TextField): Additional comments.
        * user (contrib.auth.models.User): A `BI Portal` user who created the record.
        * created (models.DateTimeField): The date & time this `Record` was created.
    """

    class AssessmentChoices:
        """Valid choices for a `Program`'s assessment."""

        RED = 1
        YELLOW = 2
        GREEN = 3
        BLUE = 4

    user = models.ForeignKey(
        get_user_model(), to_field="username", on_delete=models.CASCADE
    )
    previous_revision: models.OneToOneField = models.OneToOneField(
        "self", null=True, on_delete=models.SET_NULL
    )
    program = models.ForeignKey("program_review_tool.Program", on_delete=models.CASCADE)
    reporting_period = models.IntegerField()
    team_members = models.ManyToManyField(
        "program_review_tool.ProgramMember",
        db_table="program_review_tool_record_program_members",
    )
    pa_number = models.CharField(max_length=64)
    name = models.CharField(max_length=1028)
    segment = models.CharField(max_length=1028, default="")
    sector = models.CharField(max_length=1028, default="")
    division = models.CharField(max_length=1028, default="")
    tier = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(4)], null=True
    )
    program_phase = models.CharField(max_length=1028, default="")
    site = models.CharField(max_length=1028, default="")
    defense_financial_acquisition_regulation_clause = models.BooleanField(
        null=True, default=None
    )
    cost_and_software_data_reporting_system_clause = models.BooleanField(
        null=True, default=None
    )
    earned_value_management_system_reporting_requirement = models.CharField(
        max_length=20, default=""
    )
    contract_type = models.CharField(max_length=64, default="")
    contract_number = models.CharField(max_length=32, default="")
    contract_value = models.PositiveBigIntegerField(null=True)
    contract_start_date = models.DateField(null=True, default=None)
    contract_end_date = models.DateField(null=True, default=None)
    actual_cost_work_performed_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    budgeted_cost_work_performed_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    budgeted_cost_work_scheduled_cumulative = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    cost_performance_index_cumulative = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, default=None
    )
    schedule_performance_index_cumulative = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, default=None
    )
    budget_at_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    estimate_at_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    estimate_to_complete = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    management_reserve = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    weighted_risks_and_opportunities = models.DecimalField(
        max_digits=14, decimal_places=2, null=True, default=None
    )
    customer_assessment = models.IntegerField(
        choices=[
            (AssessmentChoices.RED, "RED"),
            (AssessmentChoices.YELLOW, "YELLOW"),
            (AssessmentChoices.GREEN, "GREEN"),
            (AssessmentChoices.BLUE, "BLUE"),
        ],
        null=True,
        default=None,
    )
    technical_assessment = models.IntegerField(
        choices=[
            (AssessmentChoices.RED, "RED"),
            (AssessmentChoices.YELLOW, "YELLOW"),
            (AssessmentChoices.GREEN, "GREEN"),
            (AssessmentChoices.BLUE, "BLUE"),
        ],
        null=True,
        default=None,
    )
    risk_assessment = models.IntegerField(
        choices=[
            (AssessmentChoices.RED, "RED"),
            (AssessmentChoices.YELLOW, "YELLOW"),
            (AssessmentChoices.GREEN, "GREEN"),
            (AssessmentChoices.BLUE, "BLUE"),
        ],
        null=True,
        default=None,
    )
    overall_program = models.IntegerField(
        choices=[
            (AssessmentChoices.RED, "RED"),
            (AssessmentChoices.YELLOW, "YELLOW"),
            (AssessmentChoices.GREEN, "GREEN"),
            (AssessmentChoices.BLUE, "BLUE"),
        ],
        null=True,
        default=None,
    )
    comments = models.TextField(null=True, default=None)

    modified = None  # type: ignore[assignment]

    def __str__(self) -> str:
        """String Representation of a `Record`."""

        return (
            f"Record(id={self.id}, program={self.pa_number}, reporting_period={self.reporting_period},"
            f" name={self.name})"
        )

    @property
    def id(self) -> int:
        """Primary Key."""

        return self.id

    class Meta:
        """Meta Class for `Record`."""

        db_table_comment = ""
        default_related_name = "records"
        indexes = [
            models.Index(fields=("reporting_period",), name="record_reporting_period"),
            models.Index(fields=("program",), name="record_program"),
            models.Index(fields=("pa_number",), name="record_pa_number"),
            models.Index(fields=("id",), name="record_id"),
        ]
        ordering = ["-reporting_period", "-created"]
        verbose_name = "program record"
        verbose_name_plural = "program records"


Record.Meta.db_table_comment = Record.__doc__  # type: ignore[assignment]
