"""
Arguments to be shared for Record's fetch
controller pytests.
"""

from datetime import date

FETCH_RECORD_USER_EMAIL: str = "Peter.Parker@harris.com"

FETCH_RECORD_PROGRAM_PA_NUMBER: str = "489AB"
FETCH_RECORD_REPORTING_PERIOD: int = 202608

FETCH_RECORD_NO_CURRENT_RECORD_FOR_REPORTING_PERIOD_REPORTING_PERIOD: int = 202606

FETCH_RECORD_NO_EXISTING_RECORD_PROGRAM_PA_NUMBER: str = "2422_CC"

FETCH_RECORD_PROGRAM_PA_NUMBER_DNE: str = "DNE_PA_NUMBER"

FETCH_RECORD_EXPECTED_RECORD_DATA: dict = {
    "id": 2,
    "pa_number": "489AB",
    "name": "AA_489AB",
    "segment": "SPACE & AIRBORNE SYSTEMS",
    "sector": "Space Systems",
    "division": "Surveillance Systems",
    "tier": 1,
    "contract_type": "FFP",
    "contract_number": "CN234739",
    "contract_value": 800000000,
    "contract_start_date": "2026-01-01",
    "contract_end_date": "2026-12-01",
    "actual_cost_work_performed_cumulative": 28.36,
    "budgeted_cost_work_performed_cumulative": 32.42,
    "budgeted_cost_work_scheduled_cumulative": 40.18,
    "cost_performance_index_cumulative": 0.08,
    "schedule_performance_index_cumulative": 0.38,
    "budget_at_complete": 62.82,
    "estimate_at_complete": 30.41,
    "estimate_to_complete": 43.23,
    "management_reserve": 50.8,
    "weighted_risks_and_opportunities": 28.82,
    "team_members": [],
    "previous_revision": None,
    "reporting_period": 202608,
    "site": "Montgomery, AL",
    "cost_and_software_data_reporting_system_clause": False,
    "defense_financial_acquisition_regulation_clause": True,
    "earned_value_management_system_reporting_requirement": "EVMS‑Level‑3",
    "program_phase": "Execution",
    "user": {
        "id": 2,
        "username": "Peter.Parker@harris.com",
        "email": "Peter.Parker@l3harris.com",
        "first_name": "Peter",
        "last_name": "Parker",
        "is_active": True,
    },
    "created": "2026-09-01T12:00:00-04:00",
    "customer_assessment": 2,
    "technical_assessment": 3,
    "risk_assessment": 3,
    "overall_program": 3,
    "comments": "Program spending is within estimated budget.",
    "is_manual_metrics_entry": False,
    "tasks": [
        {
            "id": 3,
            "name": "Task Beta",
            "description": "Initial analysis of system requirements.",
            "status": "In Progress",
            "order": 1,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202608],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": "2025-08-01",
            "archive_date": None,
        },
        {
            "id": 4,
            "name": "Task Gamma",
            "description": "Develop prototype and conduct preliminary testing.",
            "status": "Pending Review",
            "order": 2,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202608],
            "create_date": "2025-01-01",
            "target_date": "2025-05-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 5,
            "name": "Task Delta",
            "description": "Finalize design, documentation, and handover.",
            "status": "Not Started",
            "order": 3,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 1,
            "name": "Task Alpha",
            "description": "Beginning Planning.",
            "status": "Completed",
            "order": None,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2024-01-01",
            "target_date": "2025-01-01",
            "complete_date": "2025-01-01",
            "archive_date": "2025-02-01",
        },
    ],
}


FETCH_RECORD_NO_CURRENT_RECORD_FOR_REPORTING_PERIOD_EXPECTED_RECORD_DATA: dict = {
    "id": None,
    "reporting_period": 202606,
    "pa_number": "489AB",
    "name": "AA_489AB",
    "segment": "SPACE & AIRBORNE SYSTEMS",
    "sector": "Space Systems",
    "division": "Surveillance Systems",
    "tier": 1,
    "contract_number": "CN234739",
    "contract_value": 8000000000,
    "contract_start_date": "2026-01-01",
    "contract_end_date": "2026-12-01",
    "actual_cost_work_performed_cumulative": 60.4,
    "budgeted_cost_work_performed_cumulative": 32.42,
    "budgeted_cost_work_scheduled_cumulative": 40.18,
    "cost_performance_index_cumulative": 0.08,
    "schedule_performance_index_cumulative": 0.38,
    "budget_at_complete": 62.82,
    "estimate_at_complete": 30.41,
    "estimate_to_complete": 43.23,
    "management_reserve": 50.8,
    "weighted_risks_and_opportunities": 29.02,
    "team_members": [
        {
            "id": 1,
            "role": {
                "id": 1,
                "name": "PROGRAM MANAGER",
                "description": "Leads program execution and delivery, managing scope, schedule, cost, and performance.",
            },
            "user": {
                "id": 2,
                "username": "Peter.Parker@harris.com",
                "email": "Peter.Parker@l3harris.com",
                "first_name": "Peter",
                "last_name": "Parker",
                "is_active": True,
            },
            "created": "2026-01-01T11:00:00-05:00",
            "modified": "2026-01-01T11:00:00-05:00",
            "expiry_date": None,
            "program": 1,
        }
    ],
    "contract_type": "FFP",
    "site": "Montgomery, AL",
    "cost_and_software_data_reporting_system_clause": False,
    "defense_financial_acquisition_regulation_clause": True,
    "earned_value_management_system_reporting_requirement": "EVMS‑Level‑3",
    "program_phase": "Execution",
    "previous_revision": None,
    "customer_assessment": None,
    "technical_assessment": None,
    "risk_assessment": None,
    "overall_program": None,
    "comments": "",
    "is_manual_metrics_entry": True,
    "user": None,
    "created": None,
    "tasks": [
        {
            "id": 2,
            "name": "Task Beta",
            "description": "Initial analysis of system requirements.",
            "status": "Not Started",
            "order": 1,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 5,
            "name": "Task Delta",
            "description": "Finalize design, documentation, and handover.",
            "status": "Not Started",
            "order": 3,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 1,
            "name": "Task Alpha",
            "description": "Beginning Planning.",
            "status": "Completed",
            "order": None,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2024-01-01",
            "target_date": "2025-01-01",
            "complete_date": "2025-01-01",
            "archive_date": "2025-02-01",
        },
    ],
}


FETCH_RECORD_NO_EXISTING_RECORD_EXPECTED_RECORD_DATA: dict = {
    "id": None,
    "pa_number": "2422_CC",
    "name": "AAA_2422CC",
    "segment": "SPACE & AIRBORNE SYSTEMS",
    "sector": "Space Systems",
    "division": "Surveillance Systems",
    "tier": 4,
    "contract_type": "",
    "contract_number": "CN429642",
    "contract_value": 30000000,
    "contract_start_date": "2026-01-01",
    "contract_end_date": "2026-12-01",
    "actual_cost_work_performed_cumulative": 20.43,
    "budgeted_cost_work_performed_cumulative": 22.6,
    "budgeted_cost_work_scheduled_cumulative": 18.08,
    "cost_performance_index_cumulative": 0.04,
    "schedule_performance_index_cumulative": 0.2,
    "budget_at_complete": 24.0,
    "estimate_at_complete": 25.0,
    "estimate_to_complete": 26.0,
    "management_reserve": 20.3,
    "weighted_risks_and_opportunities": 12.4,
    "team_members": [
        {
            "id": 2,
            "role": {
                "id": 1,
                "name": "PROGRAM MANAGER",
                "description": "Leads program execution and delivery, managing scope, schedule, cost, and performance.",
            },
            "user": {
                "id": 2,
                "username": "Peter.Parker@harris.com",
                "email": "Peter.Parker@l3harris.com",
                "first_name": "Peter",
                "last_name": "Parker",
                "is_active": True,
            },
            "created": "2026-01-01T11:00:00-05:00",
            "modified": "2026-01-01T11:00:00-05:00",
            "expiry_date": None,
            "program": 2,
        }
    ],
    "previous_revision": None,
    "reporting_period": 202608,
    "site": "",
    "cost_and_software_data_reporting_system_clause": None,
    "defense_financial_acquisition_regulation_clause": None,
    "earned_value_management_system_reporting_requirement": "",
    "program_phase": "",
    "user": None,
    "created": None,
    "customer_assessment": None,
    "technical_assessment": None,
    "risk_assessment": None,
    "overall_program": None,
    "comments": "",
    "is_manual_metrics_entry": False,
    "tasks": [],
}

FETCH_RECORD_WITH_REFRESH_EXPECTED_RECORD_DATA: dict = {
    "id": None,
    "pa_number": "489AB",
    "name": "AA_489AB",
    "segment": "SPACE & AIRBORNE SYSTEMS",
    "sector": "Space Systems",
    "division": "Surveillance Systems",
    "tier": 1,
    "contract_type": "FFP",
    "contract_number": "CN234739",
    "contract_value": 8000000000,
    "contract_start_date": "2026-01-01",
    "contract_end_date": "2026-12-01",
    "actual_cost_work_performed_cumulative": 60.4,
    "budgeted_cost_work_performed_cumulative": 32.42,
    "budgeted_cost_work_scheduled_cumulative": 40.18,
    "cost_performance_index_cumulative": 0.08,
    "schedule_performance_index_cumulative": 0.38,
    "budget_at_complete": 62.82,
    "estimate_at_complete": 30.41,
    "estimate_to_complete": 43.23,
    "management_reserve": 50.8,
    "weighted_risks_and_opportunities": 29.02,
    "team_members": [
        {
            "id": 1,
            "role": {
                "id": 1,
                "name": "PROGRAM MANAGER",
                "description": "Leads program execution and delivery, managing scope, schedule, cost, and performance.",
            },
            "user": {
                "id": 2,
                "username": "Peter.Parker@harris.com",
                "email": "Peter.Parker@l3harris.com",
                "first_name": "Peter",
                "last_name": "Parker",
                "is_active": True,
            },
            "created": "2026-01-01T11:00:00-05:00",
            "modified": "2026-01-01T11:00:00-05:00",
            "expiry_date": None,
            "program": 1,
        }
    ],
    "previous_revision": None,
    "reporting_period": 202608,
    "site": "Montgomery, AL",
    "cost_and_software_data_reporting_system_clause": False,
    "defense_financial_acquisition_regulation_clause": True,
    "earned_value_management_system_reporting_requirement": "EVMS‑Level‑3",
    "program_phase": "Execution",
    "user": {
        "id": 2,
        "username": "Peter.Parker@harris.com",
        "email": "Peter.Parker@l3harris.com",
        "first_name": "Peter",
        "last_name": "Parker",
        "is_active": True,
    },
    "created": "2026-09-01T12:00:00-04:00",
    "customer_assessment": 2,
    "technical_assessment": 3,
    "risk_assessment": 3,
    "overall_program": 3,
    "comments": "Program spending is within estimated budget.",
    "is_manual_metrics_entry": True,
    "tasks": [
        {
            "id": 3,
            "name": "Task Beta",
            "description": "Initial analysis of system requirements.",
            "status": "In Progress",
            "order": 1,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202608],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": "2025-08-01",
            "archive_date": None,
        },
        {
            "id": 4,
            "name": "Task Gamma",
            "description": "Develop prototype and conduct preliminary testing.",
            "status": "Pending Review",
            "order": 2,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202608],
            "create_date": "2025-01-01",
            "target_date": "2025-05-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 5,
            "name": "Task Delta",
            "description": "Finalize design, documentation, and handover.",
            "status": "Not Started",
            "order": 3,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2025-01-01",
            "target_date": "2025-10-01",
            "complete_date": None,
            "archive_date": None,
        },
        {
            "id": 1,
            "name": "Task Alpha",
            "description": "Beginning Planning.",
            "status": "Completed",
            "order": None,
            "owner": "Peter.Parker@l3harris.com",
            "pa_number": "489AB",
            "reporting_period": [202604, 202608],
            "create_date": "2024-01-01",
            "target_date": "2025-01-01",
            "complete_date": "2025-01-01",
            "archive_date": "2025-02-01",
        },
    ],
}
