# Generated by Django 5.0.2 on 2025-04-14 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_role_access_access_user_access_on_granted_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("pa_number", models.CharField(max_length=64, unique=True)),
                ("sector", models.CharField(max_length=1028)),
                ("division", models.CharField(max_length=1028)),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("contract_value", models.PositiveBigIntegerField()),
                ("active_status", models.BooleanField(default=None, null=True)),
                (
                    "segment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "program",
                "verbose_name_plural": "programs",
                "db_table_comment": "",
                "default_related_name": "programs",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=512)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        db_table="program_review_tool_portfolio_programs",
                        to="program_review_tool.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "portfolio",
                "verbose_name_plural": "portfolios",
                "db_table_comment": "",
                "ordering": ["user", "-created"],
                "default_related_name": "portfolios",
            },
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["pa_number"], name="program_pa_number"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["name"], name="program_name"),
        ),
        migrations.AddIndex(
            model_name="program",
            index=models.Index(fields=["id"], name="program_id"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["user"], name="portfolio_user"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["name"], name="portfolio_name"),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["id"], name="portfolio_id"),
        ),
        migrations.AddConstraint(
            model_name="portfolio",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="portfolio_name_for_user"
            ),
        ),
    ]
