# Generated by Django 5.0.2 on 2025-07-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("success", models.BooleanField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True, null=True)),
                ("programs", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "usage",
                "verbose_name_plural": "usages",
                "db_table_comment": "Usage represents an execution of a portfolio generation.",
                "ordering": ["-created"],
                "default_related_name": "usages",
                "indexes": [
                    models.Index(fields=["user"], name="usage_user"),
                    models.Index(fields=["id"], name="usage_id"),
                ],
            },
        ),
    ]
