# Generated by Django 5.0.2 on 2025-08-19 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0002_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "program_role",
                "verbose_name_plural": "program_roles",
                "db_table_comment": (
                    """
                    `ProgramRole` represents a collection of specific roles that a
                    `ProgramMember` can have. These records provide a curated set of
                    roles on a `Program` and help to increase the efficiency and ease of
                    use of our queries.

                    A `ProgramRole` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): The name of the `ProgramRole`.
                        * description (models.CharField): The description of a role's
                            activities on a `Program`.
                        * created (models.DateTimeField): The date & time this `ProgramRole` was created.
                        * modified (models.DateTimeField): The date & time this `ProgramRole` was last modified.
                    """
                ),
                "default_related_name": "program_role",
                "indexes": [
                    models.Index(fields=["name"], name="program_role_name"),
                    models.Index(fields=["id"], name="program_role_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgramMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=None, null=True)),
                ("expiry_date", models.DateField(default=None, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_review_tool.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_review_tool.programrole",
                        to_field="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "program_member",
                "verbose_name_plural": "program_members",
                "db_table_comment": (
                    """
                    `ProgramMember` represents a team member for a `Program`,
                    designating their role as well as the status of that role
                    on the `Program`. `ProgramMember`s help to execute the
                    `Program` and drive forward its objectives. Current `ProgramMember`
                    roles include Program Manager and Program Financial Analyst.

                    A `ProgramMember` includes:
                        * id (int): An auto-generated number managed by the database.
                        * program (models.ForeignKey[program_review_tool.Program]): A `Program` within
                            `Program Review Tool`.
                        * role (models.ForeignKey[program_review_tool.ProgramRole]): The role of a `ProgramMember`
                            on a `Program`.
                        * user (models.ForeignKey[django.contrib.auth.User]): A `Program Review Tool` user who is
                            a team member of the `Program`.
                        * is_active (models.BooleanField): Whether the `User`s role is active on a `Program`.
                        * created (models.DateField): The date a `ProgramMember` was added to a `Program`.
                        * expiry_date (models.DateField): The date a `ProgramMember` is no longer active
                            on the `Program`.
                        * modified (models.DateTimeField): The date & time a `ProgramMember` record was
                            last modified.
                    """
                ),
                "default_related_name": "program_members",
                "indexes": [
                    models.Index(fields=["program"], name="program_member_program"),
                    models.Index(fields=["role"], name="program_member_role"),
                    models.Index(fields=["user"], name="program_member_user"),
                    models.Index(fields=["id"], name="program_member_id"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="programmember",
            constraint=models.UniqueConstraint(
                fields=("program", "user", "role", "expiry_date"),
                name="program_member_active_team_member",
            ),
        ),
    ]
