# Generated by Django 5.0.2 on 2025-08-19 11:02

import logging
from typing import cast

from django.db import migrations, transaction

from program_review_tool import models as ProgramReviewToolModels


def add_initial_program_roles(apps, schema_editor):
    """Add a validated set of `ProgramRole`s to the `ProgramRole` table.
    These roles are the initial set and may expand later.
    """

    LOGGER = logging.getLogger(__name__)

    ProgramRole = cast(
        ProgramReviewToolModels.ProgramRole,
        apps.get_model("program_review_tool", "ProgramRole"),
    )

    INITIAL_DATASET = [
        {
            "name": "PROGRAM MANAGER",
            "description": (
                "Leads program execution and delivery, managing scope,"
                " schedule, cost, and performance."
            ),
        },
        {
            "name": "PROGRAM FINANCIAL ANALYST",
            "description": (
                "Monitors program financials, provides cost analysis,"
                " and supports budget and forecast planning."
            ),
        },
    ]

    LOGGER.info("Ingesting initial `ProgramRole` records...")

    with transaction.atomic():
        for record in INITIAL_DATASET:
            ProgramRole.objects.create(**record)

    LOGGER.info("Ingested all `ProgramRole` records...")


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0003_programrole_programmember_and_more"),
    ]

    operations = [
        migrations.RunPython(add_initial_program_roles),
    ]
