# Generated by Django 5.0.2 on 2025-08-19 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0004_populate_program_role_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="actual_cost_work_performed_cumulative",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="budget_at_complete",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="budgeted_cost_work_performed_cumulative",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="budgeted_cost_work_scheduled_cumulative",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="contract_end_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="contract_number",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="program",
            name="contract_start_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="contract_type",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="program",
            name="cost_performance_index_cumulative",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="estimate_at_complete",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="estimate_to_complete",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="management_reserve",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="schedule_performance_index_cumulative",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="weighted_risks_and_opportunities",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="contract_value",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="division",
            field=models.CharField(default="", max_length=1028),
        ),
        migrations.AlterField(
            model_name="program",
            name="sector",
            field=models.CharField(default="", max_length=1028),
        ),
        migrations.AlterField(
            model_name="program",
            name="tier",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
