# Generated by Django 5.0.2 on 2025-08-21 16:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "program_review_tool",
            "0005_alter_program_table_for_program_performance_review",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("reporting_period", models.IntegerField()),
                ("pa_number", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=1028)),
                ("segment", models.CharField(default="", max_length=1028)),
                ("sector", models.CharField(default="", max_length=1028)),
                ("division", models.CharField(default="", max_length=1028)),
                (
                    "tier",
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("program_phase", models.CharField(default="", max_length=1028)),
                ("site", models.CharField(default="", max_length=1028)),
                (
                    "defense_financial_acquisition_regulation_clause",
                    models.BooleanField(default=None, null=True),
                ),
                (
                    "cost_and_software_data_reporting_system_clause",
                    models.BooleanField(default=None, null=True),
                ),
                (
                    "earned_value_management_system_reporting_requirement",
                    models.CharField(default="", max_length=20),
                ),
                ("contract_type", models.CharField(default="", max_length=64)),
                ("contract_number", models.CharField(default="", max_length=32)),
                ("contract_value", models.PositiveBigIntegerField(null=True)),
                ("contract_start_date", models.DateField(default=None, null=True)),
                ("contract_end_date", models.DateField(default=None, null=True)),
                (
                    "actual_cost_work_performed_cumulative",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "budgeted_cost_work_performed_cumulative",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "budgeted_cost_work_scheduled_cumulative",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "cost_performance_index_cumulative",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "schedule_performance_index_cumulative",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "budget_at_complete",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "estimate_at_complete",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "estimate_to_complete",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "management_reserve",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "weighted_risks_and_opportunities",
                    models.DecimalField(
                        decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "customer_assessment",
                    models.IntegerField(
                        choices=[
                            (1, "RED"),
                            (2, "YELLOW"),
                            (3, "GREEN"),
                            (4, "BLUE"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "technical_assessment",
                    models.IntegerField(
                        choices=[
                            (1, "RED"),
                            (2, "YELLOW"),
                            (3, "GREEN"),
                            (4, "BLUE"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "risk_assessment",
                    models.IntegerField(
                        choices=[
                            (1, "RED"),
                            (2, "YELLOW"),
                            (3, "GREEN"),
                            (4, "BLUE"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "overall_program",
                    models.IntegerField(
                        choices=[
                            (1, "RED"),
                            (2, "YELLOW"),
                            (3, "GREEN"),
                            (4, "BLUE"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("comments", models.TextField(default=None, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_review_tool.program",
                    ),
                ),
                (
                    "previous_revision",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="program_review_tool.record",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        db_table="program_review_tool_record_program_members",
                        to="program_review_tool.programmember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "verbose_name": "program record",
                "verbose_name_plural": "program records",
                "db_table_comment": (
                    """
                    `Record` represents a monthly snapshot of a `Program` within L3Harris Technologies.
                    These efforts leverage subjective analysis and key financial metrics to track
                    long-term program health.

                    A `Record` includes:
                        * id (int): An auto-generated number managed by the database.
                        * previous_revision (directory.models.Record): A reference to its previous
                            revision.
                        * program (models.ForeignKey): The associated `Program`.
                        * reporting_period (models.IntegerField): The reporting period (e.g., `202306` for June 2023).
                        * team_members (models.ManyToManyField[program_review_tool.models.ProgramMember]):
                            The team members assigned to the `Program`.
                        * pa_number (models.CharField): A unique identifier for a program
                            generated by the Finance department.
                        * name (models.CharField): The name of the `Program`.
                        * segment (users.Segment): An organizational unit of L3Harris Technologies.
                        * sector (models.CharField): An organizational unit of a segment
                            (eg. Space and Airborne Systems).
                        * division (models.CharField): An organizational unit of a sector
                            (eg. Space Systems).
                        * tier (models.PositiveSmallIntegerField): Describes the mission importance
                            and risk of a `Program`. Limited to the range of 1-4, where 1 is
                            considered the highest tier.
                        * program_phase (models.CharField): The current phase of the `Program`.
                        * site (models.CharField): The L3Harris Technologies site associated with the `Program`.
                        * defense_financial_acquisition_regulation_clause (models.BooleanField): Indicates whether the DFARS clause is applicable.
                        * cost_and_software_data_reporting_system_clause (models.BooleanField): Indicates whether the CSDR clause is applicable.
                        * earned_value_management_system_reporting_requirement (models.CharField): The EVMS reporting requirement.
                        * contract_type (models.CharField): The classification of the
                            contract (e.g., FFP, CPFF, T&M) that defines terms of pricing,
                            risk, and reimbursement.
                        * contract_number (models.CharField): The unique identifier assigned
                            to a contractual agreement between the customer and L3Harris
                            technologies.
                        * contract_value (models.PositiveBigIntegerField): The dollar value
                            assigned to the `Program`.
                        * contract_start_date (models.DateField): The date on which the contractual
                            period of performance officially begins.
                        * contract_end_date (models.DateField): The date on which the contractual period of
                            performance is scheduled to conclude.
                        * actual_cost_work_performed_cumulative (models.DecimalField): The total actual cost
                            incurred for all completed work up to the reporting period.
                        * budgeted_cost_work_performed_cumulative (models.DecimalField): The cumulative value
                            of the budgeted cost for completed work as of the reporting period.
                        * budgeted_cost_work_scheduled_cumulative (models.DecimalField): The cumulative value
                            of the budgeted cost for work that was scheduled to be completed by the
                            reporting period.
                        * cost_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ ACWP) that
                            measures cost efficiency in executing the `Program`.
                        * schedule_performance_index_cumulative (models.DecimalField): A ratio (BCWP ÷ BCWS)
                            that measures schedule efficiency in completing the planned work.
                        * budget_at_complete (models.DecimalField): The total budgeted cost for the
                            entire scope of work as defined in the baseline plan.
                        * estimate_at_complete (models.DecimalField): The current forecast of the total
                            expected cost required to complete the `Program`.
                        * estimate_to_complete (models.DecimalField): The projected additional cost needed
                            to complete the remaining `Program` work (EAC - ACWP).
                        * management_reserve (models.DecimalField): A budget set aside by management to cover
                            unforeseen risks or changes outside the scope of baseline work.
                        * weighted_risks_and_opportunities (models.DecimalField): The net financial impact of
                            risks and opportunities, weighted by their probability of occurrence.
                        * customer_assessment (models.IntegerField): The program manager's subjective customer assessment(1-4).
                        * technical_assessment (models.IntegerField): The program manager's subjective technical assessment (1-4).
                        * risk_assessment (models.IntegerField): The program manager's subjective risk assessment (1-4).
                        * overall_program (models.IntegerField): The program manager's subjective overall program assessment (1-4).
                        * comments (models.TextField): Additional comments.
                        * user (contrib.auth.models.User): A `BI Portal` user who created the record.
                        * created (models.DateTimeField): The date & time this `Record` was created.
                    """
                ),
                "ordering": ["-reporting_period", "-created"],
                "default_related_name": "records",
                "indexes": [
                    models.Index(
                        fields=["reporting_period"], name="record_reporting_period"
                    ),
                    models.Index(fields=["program"], name="record_program"),
                    models.Index(fields=["pa_number"], name="record_pa_number"),
                    models.Index(fields=["id"], name="record_id"),
                ],
            },
        ),
    ]
