# Generated by Django 5.0.2 on 2025-08-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0006_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmember",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="program_review_tool.programrole",
            ),
        ),
    ]
