# Generated by Django 5.0.2 on 2025-09-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0007_alter_programmember_table_role_field"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="programmember",
            table_comment="""
                `ProgramMember` represents a team member for a `Program`,
                designating their role on the `Program`. `ProgramMember`s
                help to execute the `Program` and drive forward its objectives.
                Current `ProgramMember` roles include Program Manager and
                Program Financial Analyst.

                A `ProgramMember` includes:
                    * id (int): An auto-generated number managed by the database.
                    * program (models.ForeignKey[program_review_tool.Program]): A `Program` within
                        `Program Review Tool`.
                    * role (models.ForeignKey[program_review_tool.ProgramRole]): The role of a `ProgramMember`
                        on a `Program`.
                    * user (models.ForeignKey[django.contrib.auth.User]): A `Program Review Tool` user who is
                        a team member of the `Program`.
                    * created (models.DateField): The date a `ProgramMember` was added to a `Program`.
                    * expiry_date (models.DateField): The date a `ProgramMember` is no longer active
                        on the `Program`.
                    * modified (models.DateTimeField): The date & time a `ProgramMember` record was
                        last modified.
                """,
        ),
        migrations.RemoveField(
            model_name="programmember",
            name="is_active",
        ),
    ]
