# Generated by Django 5.0.2 on 2025-09-24 18:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0008_remove_is_active_from_programmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("description", models.TextField()),
                ("pa_number", models.CharField(max_length=64)),
                (
                    "reporting_period",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                ("order", models.IntegerField(null=True)),
                ("status", models.CharField(max_length=512)),
                ("create_date", models.DateField()),
                ("target_date", models.DateField()),
                ("complete_date", models.DateField(default=None, null=True)),
                ("archive_date", models.DateField(default=None, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "previous_revision",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="program_review_tool.task",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="program_review_tool.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "db_table_comment": "`Task` represents a step in a plan for a program to return to green. Each `Task` created by a `Program_Member` is stored within our `Task` model. Progress of a `Task` is tracked through reporting periods, with a `Task`s status finalized at the end of the period so a history can be traced. A program's `Task`s are pulled with the most current `Record` in a reporting period, to give an overall status of a program's health and progress.A `Task` includes:    * id (int): An auto-generated number managed by the database.    * previous_revision (directory.models.Task): A reference to its previous        revision.    * program (models.ForeignKey): The associated `Program`.    * reporting_period (Array[models.IntegerField]): The reporting periods (e.g., `202306` for June 2023)        where the task exists and has remained unchanged.    * pa_number (models.CharField): A unique identifier for a program        generated by the Finance department.    * order (models.IntegerField): The order in which this task should appear.    * name (models.CharField): The name of the task.    * description (models.CharField): A description of the the task.    * owner (auth.User): A `User` who is in charge of seeing the task completed,        does not have to be a `Program_Member`.    * status (models.CharField): A description of the current state of the task.    * create_date (models.DateField): The date this `Task` was originally created.    * target_date (models.DateField): The date this `Task` should be completed by.    * complete_date (models.DateField): The date this `Task` has been completed by.    * archive_date (models.DateField): The date this `Task` has been archived.",
                "ordering": ["order", "-archive_date"],
                "default_related_name": "tasks",
                "indexes": [
                    models.Index(fields=["pa_number"], name="task_pa_number"),
                    models.Index(fields=["id"], name="task_id"),
                    models.Index(
                        fields=["reporting_period"], name="task_reporting_periods"
                    ),
                ],
            },
        ),
    ]
