# Generated by Django 5.0.2 on 2025-10-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0009_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="is_manual_metrics_entry",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="record",
            name="is_manual_metrics_entry",
            field=models.BooleanField(default=False),
        ),
    ]
