# Generated by Django 5.0.2 on 2025-10-24 19:37

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        (
            "program_review_tool",
            "0010_alter_program_and_programmember_tables_adding_is_manual_mectrics_entry_field",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=512,
                unique=False,
            ),
        ),
    ]
