# Generated by Django 5.0.2 on 2025-10-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0011_alter_task_name_not_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="task_name",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
