# Generated by Django 5.0.2 on 2026-01-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0012_alter_task_create_task_name"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE users_profile ALTER COLUMN uid TYPE character varying(256);"
            ],
            reverse_sql=[
                (
                    "ALTER TABLE users_profile ALTER COLUMN uid TYPE character varying(10);",
                )
            ],
        )
    ]