# Generated by Django 5.0.2 on 2026-03-26 12:31

import logging
from typing import cast

from django.db import migrations

from users import models as UserModels


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0013_alter_profile_uid_max_length"),
    ]

    def add_space_and_mission_systems_segment(apps, schema_editor):
        """Add the SPACE & MISSION SYSTEMS segment to the Segment table."""

        LOGGER = logging.getLogger(__name__)

        Segment = cast(UserModels.Segment, apps.get_model("users", "Segment"))
        segment_id = 5
        segment_name = "SPACE & MISSION SYSTEMS"
        segment_description = (
            "SPACE & MISSION SYSTEMS is a segment of business at L3Harris Technologies, inc. "
            "that focuses on providing space and mission systems solutions to customers. This "
            "segment includes a wide range of products and services, such as satellite "
            "communications, space-based sensors, and mission planning and execution support."
        )
        if not Segment.objects.using("prt").filter(name=segment_name).exists():
            LOGGER.info(f"Adding '{segment_name}' segment to the database...")
            Segment.objects.using("prt").create(
                id=segment_id, name=segment_name, description=segment_description
            )

    operations = [
        migrations.RunPython(add_space_and_mission_systems_segment),
    ]
