# Generated by Django 5.0.2 on 2026-05-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program_review_tool", "0014_add_space_and_mission_systems_segment"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("job_name", models.CharField(max_length=512)),
                ("user", models.CharField(max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("duration", models.IntegerField(default=0, null=True)),
                ("error_msg", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "jobrun",
                "db_table_comment": "",
                "ordering": ["-finished_at"],
                "default_related_name": "jobruns",
                "indexes": [
                    models.Index(fields=["job_name"], name="job_name"),
                    models.Index(fields=["status"], name="job_status"),
                    models.Index(fields=["error_msg"], name="job_error_message"),
                ],
            },
        ),
    ]
