include:
    - ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/db/db.docker-compose.yml
    - ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/cache/caches.docker-compose.yml

x-logging-settings: &logging-settings
    logging:
        driver: "json-file"
        options:
            max-size: "256k"
            max-file: "3"

services:
    api:
        image: ${APP_NAME}-development-api:${DOCKER_COMPOSE_BUILD_TAG}

        build:
            context: ${DOCKER_COMPOSE_PROJECT_ROOT}/api/
            dockerfile: Dockerfile
            target: ${DOCKER_COMPOSE_API_BUILD_TARGET}
            args:
                APP_NAME: ${APP_NAME}
                CA_CERTIFICATE_FOR_API: ${CA_CERTIFICATE_FOR_API}
                USER: ${USER}
                UID: ${UID}
                PASSWORD: ${PASSWORD}
            tags:
                - ${APP_NAME}-development-api:${DOCKER_COMPOSE_BUILD_TAG}
        restart: unless-stopped

        container_name: ${APP_NAME}-api-${USER}
        depends_on:
            - database
            - cache
            - channel
        <<: *logging-settings
        environment:
            APP_NAME: ${APP_NAME}
            BUILD: ${BUILD}
            CONNECTION: ${CONNECTION}
            CONTAINER_PASSWORD: ${PASSWORD}
            DNS_NAME: ${DNS_NAME}
            SCHEME: ${SCHEME}
            SERVER_HOST: ${SERVER_HOST}
            SERVER_PORT: ${SERVER_PORT}
            WEB_HOST: ${WEB_HOST}
            WEB_PORT: ${WEB_PORT}
            POSTGRES_NAME: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_ATOMIC_REQUESTS: ${POSTGRES_ATOMIC_REQUESTS}
            POSTGRES_PROGRAM_REVIEW_TOOL_NAME: ${POSTGRES_PROGRAM_REVIEW_TOOL_NAME}
            POSTGRES_PROGRAM_REVIEW_TOOL_USER: ${POSTGRES_PROGRAM_REVIEW_TOOL_USER}
            POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD: ${POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD}
            FDW_DATABASE_NAME: ${FDW_DATABASE_NAME}
            FDW_DATABASE_USER: ${FDW_DATABASE_USER}
            FDW_DATABASE_PASSWORD: ${FDW_DATABASE_PASSWORD}
            FDW_DATABASE_HOST: ${FDW_DATABASE_HOST}
            FDW_DATABASE_PORT: ${FDW_DATABASE_PORT}
            AXIS_DATABASE_NAME: ${AXIS_DATABASE_NAME}
            AXIS_DATABASE_USER: ${AXIS_DATABASE_USER}
            AXIS_DATABASE_PASSWORD: ${AXIS_DATABASE_PASSWORD}
            AXIS_DATABASE_HOST: ${AXIS_DATABASE_HOST}
            AXIS_DATABASE_PORT: ${AXIS_DATABASE_PORT}
            EXTERNAL_SOURCE_DATABASE: ${EXTERNAL_SOURCE_DATABASE}
            REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}
            REDIS_CACHE_HOST: ${REDIS_CACHE_HOST}
            REDIS_CACHE_PORT: ${REDIS_CACHE_PORT}
            REDIS_CHANNEL_PASSWORD: ${REDIS_CHANNEL_PASSWORD}
            REDIS_CHANNEL_HOST: ${REDIS_CHANNEL_HOST}
            REDIS_CHANNEL_PORT: ${REDIS_CHANNEL_PORT}
            USE_NOTEBOOKS: ${USE_NOTEBOOKS}
            ADMINS: ${ADMINS}
            DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
            LANGUAGE_CODE: ${LANGUAGE_CODE}
            PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS: ${PROGRAM_REVIEW_EXPORT_CACHE_TIMEOUT_SECONDS}
            SECRET_KEY: ${SECRET_KEY}
            SERVER_LOG_LEVEL: ${SERVER_LOG_LEVEL}
            SERVER_SECURE_SSL_REDIRECT: ${SERVER_SECURE_SSL_REDIRECT}
            SERVER_TIME_ZONE: ${SERVER_TIME_ZONE}
            SERVER_CACHE_TIMEOUT: ${SERVER_CACHE_TIMEOUT}
            DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
            LDAP_SEARCH_ENDPOINT: ${LDAP_SEARCH_ENDPOINT}
            SSO_ORIGIN: ${SSO_ORIGIN}
            SSO_NAME: ${SSO_NAME}
            SSO_DEVELOPMENT_USER_FIRST_NAME: ${SSO_DEVELOPMENT_USER_FIRST_NAME}
            SSO_DEVELOPMENT_USER_LAST_NAME: ${SSO_DEVELOPMENT_USER_LAST_NAME}
            SSO_SERVICE_ENCRYPTION_KEY: ${SSO_SERVICE_ENCRYPTION_KEY}
            SWAGGER_PORT: ${SWAGGER_PORT}
            TABLEAU_PERSONAL_ACCESS_TOKENS: ${TABLEAU_PERSONAL_ACCESS_TOKENS}
            TABLEAU_SERVER: ${TABLEAU_SERVER}
            AZURE_POWERBI_URI: ${AZURE_POWERBI_URI}
            AZURE_POWERBI_URI_MYORG: ${AZURE_POWERBI_URI_MYORG}
            AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
            AZURE_TENANT_ID:  ${AZURE_TENANT_ID}
            AZURE_SHARED_SECRET_ID: ${AZURE_SHARED_SECRET_ID}
            AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
            AZURE_TOKEN_CACHE_KEY: ${AZURE_TOKEN_CACHE_KEY}
            AZURE_TOKEN_CACHE_KEY_EXPIRES_IN: ${AZURE_TOKEN_CACHE_KEY_EXPIRES_IN}
            AZURE_TOKEN_CACHE_KEY_EXPIRES_ON: ${AZURE_TOKEN_CACHE_KEY_EXPIRES_ON}
            AZURE_AUTH_CACHE_TIMEOUT: ${AZURE_AUTH_CACHE_TIMEOUT}
            PBI_SLIDE_CONFIG_PATH: ${PBI_SLIDE_CONFIG_PATH}
            ENABLE_DEBUGPY: ${ENABLE_DEBUGPY:-false}
        ports:
            - ${SERVER_PORT}:8080
            - ${NOTEBOOK_PORT}:8888
            - ${API_DEBUG_PORT}:${API_DEBUG_PORT} 
        volumes:
            # Mount local development files into container.
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/api/src:/apps/${APP_NAME}/
            # Mount ssh directory to enable ssh.
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/.ssh:/home/${USER}/.ssh:ro
            # This volume is for hosting media files.
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/storage/media:/apps/${APP_NAME}/manager/storage/media
            # This volume is for fixing SSL CA Certs inside the container.
            - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro        
