"""
Arguments to be shared for Request's fetch
controller pytests.
"""

from typing import List


FETCH_REQUEST_ALL_VALID_IDS: List[int] = [1, 2, 3, 4, 5, 6]

FETCH_REQUEST_BY_ID_REQUEST_ID: int = 1

FETCH_REQUEST_NON_ARCHIVED_REQUEST_IDS: List[int] = [1, 2, 3, 4, 6]

FETCH_REQUEST_WITH_ORIGINATOR_USER_EMAIL: str = "Ben.Parker@harris.com"
FETCH_REQUEST_WITH_ORIGINATOR_REQUEST_IDS: List[int] = [2, 4, 6]

FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_STAGE_LEVELS: List[int] = [99]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_REQUEST_IDS: List[int] = [4, 6]

FETCH_REQUEST_WITH_ORIGINATOR_AND_SUBFUNCTIONS_SUBFUNCTIONS: List[int] = [3, 6]
FETCH_REQUEST_WITH_ORIGINATOR_AND_SUBFUNCTIONS_REQUEST_IDS: List[int] = [2, 4]

FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_STATUS_STAGE_LEVELS: List[int] = [2]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_STATUS_STATUS: str = "PENDING"
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_STATUS_REQUEST_IDS: List[int] = [2]

FETCH_REQUEST_WITH_ORIGINATOR_SUBFUNCTIONS_AND_STATUS_SUBFUNCTIONS: List[int] = [3]
FETCH_REQUEST_WITH_ORIGINATOR_SUBFUNCTIONS_AND_STATUS_STATUS: str = "PENDING"
FETCH_REQUEST_WITH_ORIGINATOR_SUBFUNCTIONS_AND_STATUS_REQUEST_IDS: List[int] = [2]

FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_STAGE_LEVELS: List[int] = [99]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_SUBFUNCTIONS: List[int] = [
    5,
    6,
]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_REQUEST_IDS: List[int] = [
    4,
    6,
]

FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_STAGE_LEVELS: List[
    int
] = [2]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_SUBFUNCTIONS: List[
    int
] = [
    3,
    6,
]
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_STATUS: str = (
    "PENDING"
)
FETCH_REQUEST_WITH_ORIGINATOR_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_REQUEST_IDS: List[
    int
] = [2]

FETCH_REQUEST_AT_STAGE_STAGE_LEVELS: List[int] = [99]
FETCH_REQUEST_AT_STAGE_REQUEST_IDS: List[int] = [3, 4, 6]

FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_STAGE_LEVELS: List[int] = [2]
FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_SUBFUNCTIONS: List[int] = [3]
FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_REQUEST_IDS: List[int] = [2]

FETCH_REQUEST_AT_STAGE_WITH_STATUS_STAGE_LEVELS: List[int] = [99]
FETCH_REQUEST_AT_STAGE_WITH_STATUS_STATUS: str = "APPROVED"
FETCH_REQUEST_AT_STAGE_WITH_STATUS_REQUEST_IDS: List[int] = [3, 4, 6]

FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_STAGE_LEVELS: List[int] = [2, 99]
FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_SUBFUNCTIONS: List[int] = [
    3,
    5,
    6,
]
FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_STATUS: str = "APPROVED"
FETCH_REQUEST_AT_STAGE_WITH_SUBFUNCTIONS_AND_STATUS_REQUEST_IDS: List[int] = [4, 6]

FETCH_REQUEST_WITH_SUBFUNCTIONS_SUBFUNCTIONS: List[int] = [3, 5, 6]
FETCH_REQUEST_WITH_SUBFUNCTIONS_REQUEST_IDS: List[int] = [4, 6, 2]

FETCH_REQUEST_WITH_SUBFUNCTIONS_AND_STATUS_SUBFUNCTIONS: List[int] = [3]
FETCH_REQUEST_WITH_SUBFUNCTIONS_AND_STATUS_STATUS: str = "PENDING"
FETCH_REQUEST_WITH_SUBFUNCTIONS_AND_STATUS_REQUEST_IDS: List[int] = [2]

FETCH_REQUEST_WITH_STATUS_STATUS: str = "PENDING"
FETCH_REQUEST_WITH_STATUS_REQUEST_IDS: List[int] = [1, 2]

FETCH_REQUEST_WITH_PAGE_PAGE_NUMBER: int = 1
FETCH_REQUEST_WITH_PAGE_REQUEST_IDS: List[int] = [1, 2, 3, 4, 6]

FETCH_REQUEST_WITH_LIMIT_LIMIT: int = 2
FETCH_REQUEST_WITH_LIMIT_REQUEST_IDS: List[int] = [2, 1]

FETCH_REQUEST_WITH_PAGE_AND_LIMIT_PAGE_NUMBER: int = 1
FETCH_REQUEST_WITH_PAGE_AND_LIMIT_LIMIT: int = 1
FETCH_REQUEST_WITH_PAGE_AND_LIMIT_REQUEST_IDS: List[int] = [1]

FETCH_REQUEST_WITH_PAGE_NUMBER_EXCEEDING_PAGE_COUNT_PAGE_NUM: int = 300
FETCH_REQUEST_WITH_PAGE_NUMBER_EXCEEDING_PAGE_COUNT_EXPECTED_REQUESTS_COUNT: int = 0

FETCH_REQUEST_BY_ID_REQUEST_ID_DNE: int = 999

FETCH_REQUEST_WITH_ORIGINATOR_DNE_USER_EMAIL: str = "DNE.User@harris.com"

FETCH_REQUEST_WITH_ORIGINATOR_ACCESS_DNE_USER_EMAIL: str = "Miles.Morales@harris.com"
