include:
    - ${DOCKER_COMPOSE_PROJECT_ROOT}/docker/services/cache/caches.docker-compose.yml

x-logging-settings: &logging-settings
    logging:
        driver: "json-file"
        options:
            max-size: "256k"
            max-file: "3"

services:
    api:
        image: ${APP_NAME}-production-api:${DOCKER_COMPOSE_BUILD_TAG}
        build:
            context: ${DOCKER_COMPOSE_PROJECT_ROOT}/api/
            dockerfile: Dockerfile
            target: ${DOCKER_COMPOSE_API_BUILD_TARGET}
            args:
                APP_NAME: ${APP_NAME}
                CA_CERTIFICATE_FOR_API: ${CA_CERTIFICATE_FOR_API}
                USER: ${USER}
                UID: ${UID}
                PASSWORD: ${PASSWORD}
            tags:
                - ${APP_NAME}-production-api:${DOCKER_COMPOSE_BUILD_TAG}
        restart: unless-stopped
        container_name: ${APP_NAME}-api-${USER}
        depends_on:
            - cache
            - channel
        <<: *logging-settings
        environment:
            APP_NAME: ${APP_NAME}
            BUILD: ${BUILD}
            SCHEME: ${SCHEME}
            SERVER_HOST: ${SERVER_HOST}
            SERVER_PORT: ${SERVER_PORT}
            WEB_HOST: ${WEB_HOST}
            WEB_PORT: ${WEB_PORT}
            POSTGRES_NAME: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_PORT: ${POSTGRES_PORT}
            POSTGRES_ATOMIC_REQUESTS: ${POSTGRES_ATOMIC_REQUESTS}
            POSTGRES_PROGRAM_REVIEW_TOOL_NAME: ${POSTGRES_PROGRAM_REVIEW_TOOL_NAME}
            POSTGRES_PROGRAM_REVIEW_TOOL_USER: ${POSTGRES_PROGRAM_REVIEW_TOOL_USER}
            POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD: ${POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD}
            FDW_DATABASE_NAME: ${FDW_DATABASE_NAME}
            FDW_DATABASE_USER: ${FDW_DATABASE_USER}
            FDW_DATABASE_PASSWORD: ${FDW_DATABASE_PASSWORD}
            FDW_DATABASE_HOST: ${FDW_DATABASE_HOST}
            FDW_DATABASE_PORT: ${FDW_DATABASE_PORT}
            AXIS_DATABASE_NAME: ${AXIS_DATABASE_NAME}
            AXIS_DATABASE_USER: ${AXIS_DATABASE_USER}
            AXIS_DATABASE_PASSWORD: ${AXIS_DATABASE_PASSWORD}
            AXIS_DATABASE_HOST: ${AXIS_DATABASE_HOST}
            AXIS_DATABASE_PORT: ${AXIS_DATABASE_PORT}
            REDIS_CACHE_PASSWORD: ${REDIS_CACHE_PASSWORD}
            REDIS_CACHE_HOST: ${REDIS_CACHE_HOST}
            REDIS_CACHE_PORT: ${REDIS_CACHE_PORT}
            REDIS_CHANNEL_PASSWORD: ${REDIS_CHANNEL_PASSWORD}
            REDIS_CHANNEL_HOST: ${REDIS_CHANNEL_HOST}
            REDIS_CHANNEL_PORT: ${REDIS_CHANNEL_PORT}
            ADMINS: ${ADMINS}
            DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
            LANGUAGE_CODE: ${LANGUAGE_CODE}
            SECRET_KEY: ${SECRET_KEY}
            SERVER_LOG_LEVEL: ${SERVER_LOG_LEVEL}
            SERVER_SECURE_SSL_REDIRECT: ${SERVER_SECURE_SSL_REDIRECT}
            SERVER_TIME_ZONE: ${SERVER_TIME_ZONE}
            DATA_ENCRYPTION_KEY: ${DATA_ENCRYPTION_KEY}
            LDAP_SEARCH_ENDPOINT: ${LDAP_SEARCH_ENDPOINT}
            SSO_ORIGIN: ${SSO_ORIGIN}
            SSO_SERVICE_ENCRYPTION_KEY: ${SSO_SERVICE_ENCRYPTION_KEY}
        ports:
            - ${SERVER_PORT}:8080
        volumes:
            # This volume is for hosting static files.
            - ${DOCKER_COMPOSE_PROJECT_ROOT}/api/src/manager/storage:/apps/${APP_NAME}/manager/storage
            # This volume is for hosting media files.
            - /apps/${APP_NAME}/storage/media:/apps/${APP_NAME}/manager/storage/media
            # This volume is for fixing SSL CA Certs inside the container.
            - /etc/ssl/certs/ca-bundle.crt:/etc/ssl/certs/ca-bundle.crt:ro
