#!/bin/bash
set -e
set -u

echo "Creating user and database '$POSTGRES_PROGRAM_REVIEW_TOOL_NAME'"

if [[ -n "${POSTGRES_PROGRAM_REVIEW_TOOL_NAME}" && -n "${POSTGRES_PROGRAM_REVIEW_TOOL_USER}" && -n "${POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD}" ]]; then
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER $POSTGRES_PROGRAM_REVIEW_TOOL_USER;
        CREATE DATABASE $POSTGRES_PROGRAM_REVIEW_TOOL_NAME;
        GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_PROGRAM_REVIEW_TOOL_NAME TO $POSTGRES_PROGRAM_REVIEW_TOOL_USER;
        ALTER USER $POSTGRES_PROGRAM_REVIEW_TOOL_USER WITH PASSWORD '$POSTGRES_PROGRAM_REVIEW_TOOL_PASSWORD';
        ALTER USER $POSTGRES_PROGRAM_REVIEW_TOOL_USER CREATEDB;
        ALTER USER $POSTGRES_PROGRAM_REVIEW_TOOL_USER WITH SUPERUSER;
EOSQL
fi