# Generated by Django 5.0.2 on 2024-08-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("disposition", models.CharField(max_length=512)),
                ("justification", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "disposition",
                "verbose_name_plural": "dispositions",
                "db_table_comment": (
                    """
                    `Disposition` represents a vote by a BI Portal admin
                    on a request to add/modify a directory resource. `Resource`s
                    transition from their initial `Stage` inevitably to their
                    final `Stage`, where a request for an addition or change is
                    ultimately approved or rejected. Dispositions are the primary
                    catalyst for such transitions. Once a request receives sufficient
                    dispositions, a request transitions to its next stage. `Disposition`s
                    should never be deleted.

                    A `Disposition` includes:
                        * id (int): An auto-generated number managed by the database.
                        * approver (users.models.Access): Access of the BI Portal admin
                            that voted.
                        * disposition (models.CharField): A vote for a request.
                        * justification (models.TextField): A reason as to why a vote was
                            ultimately made.
                        * transition (request.models.Transition): The related `Transition`
                            for this `Disposition`.
                        * created (models.DateTimeField): The date & time this `Disposition`
                            was created.
                    """
                ),
                "ordering": ["approver", "transition"],
                "default_related_name": "dispositions",
            },
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=512)),
            ],
            options={
                "verbose_name": "request",
                "verbose_name_plural": "requests",
                "db_table_comment": (
                    """
                    `Request` represents a request made by a user, to add, modify or
                    potentially delete a directory resource. `Resource`s transition
                    from their initial `Stage` inevitably to their final `Stage`,
                    where a request for an addition or change is ultimately approved
                    or rejected. A `Resource` is only visible (active) to a user once
                    its associated request has transitioned from its initial stage to
                    its final stage where it has been approved.

                    A `Request` includes:
                        * id (int): An auto-generated number managed by the database.
                        * resource (directory.models.Resource): A directory resource.
                        * originator (users.models.Access): Access of the user who
                            created this `Request`.
                        * status (models.CharField): Status of the `Request`.
                        * created (models.DateTimeField): The date & time this `Request` was
                            created.
                        * modified (models.DateTimeField): The date & time this `Request` was
                            last modified.
                    """
                ),
                "ordering": ["-resource"],
                "default_related_name": "requests",
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("level", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "stage",
                "verbose_name_plural": "stages",
                "db_table_comment": (
                    """
                    `Stage` represents a single phase in the resource request
                    workflow. These stages help to determine the progression
                    of a `Resource` through that workflow, and thus along
                    with `Transition`s permis a `Resource` to be added,
                    modified or potentially deleted.

                    A `Stage` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): Name of the stage.
                        * description (models.TextField): Description of the stage.
                        * level (models.PositiveIntegerField): An immutable numerical
                            representation of the stage.
                    """
                ),
                "ordering": ["level"],
                "default_related_name": "stages",
            },
        ),
        migrations.CreateModel(
            name="Transition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "transition",
                "verbose_name_plural": "transitions",
                "db_table_comment": (
                    """
                    `Transition` represents the transition of a `Resource`
                    from one `Stage` to another. `Resource`s transition from
                    their initial `Stage` inevitably to their final `Stage`,
                    where a request for an addition or change is ultimately
                    approved or rejected.

                    A `Transition` includes:
                        * id (int): An auto-generated number managed by the database.
                        * request (request.models.Request): `Request` that is being tracked.
                        * stage (request.models.Stage): The stage of the transition.
                        * previous_transition (request.models.Transition): The `Request`'s
                            previous `Transition`.
                        * created (models.DateTimeField): The date & time this `Transition`
                            was created.
                    """
                ),
                "ordering": ["id"],
                "default_related_name": "transitions",
            },
        ),
    ]
