# Generated by Django 5.0.2 on 2024-08-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
        ("request", "0001_initial"),
        ("users", "0003_role_access_access_user_access_on_granted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="disposition",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.access"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="originator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.access"
            ),
        ),
        migrations.AddField(
            model_name="request",
            name="resource",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="directory.resource"
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["level"], name="stage_level"),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["name"], name="stage_name"),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["id"], name="stage_id"),
        ),
        migrations.AddField(
            model_name="transition",
            name="previous_transition",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="request.transition",
            ),
        ),
        migrations.AddField(
            model_name="transition",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="request.request"
            ),
        ),
        migrations.AddField(
            model_name="transition",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="request.stage"
            ),
        ),
        migrations.AddField(
            model_name="disposition",
            name="transition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="request.transition"
            ),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["resource"], name="request_resource"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["originator"], name="request_originator"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["id"], name="request_id"),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["stage"], name="transition_stage"),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["request"], name="transition_request"),
        ),
        migrations.AddIndex(
            model_name="transition",
            index=models.Index(fields=["id"], name="transition_id"),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(fields=["transition"], name="disposition_transition"),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(fields=["disposition"], name="disposition_disposition"),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(fields=["approver"], name="disposition_approver"),
        ),
        migrations.AddIndex(
            model_name="disposition",
            index=models.Index(fields=["id"], name="disposition_id"),
        ),
    ]
