# Generated by Django 5.0.2 on 2025-06-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={
                "default_related_name": "requests",
                "ordering": ["-modified"],
                "verbose_name": "request",
                "verbose_name_plural": "requests",
            },
        ),
    ]
