"""
Django settings for manager project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# pylint: disable=too-few-public-methods

import os
import sys
from pathlib import Path

from django.http import HttpRequest

from manager import db, cache

# Name of application. It is used to customize the name of
# the project and register application with SSO service.
APP_NAME = os.getenv("APP_NAME", "change-to-your-app-name")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/


# Specify valid build for application.
class ApplicationBuild:
    """Supported Application Builds."""

    PRODUCTION = "production"
    STAGING = "staging"
    DEVELOPMENT = "development"
    TEST = "test"

    VALID_BUILDS = (PRODUCTION, STAGING, DEVELOPMENT, TEST)


# Specify valid web protocols for application.
class WebProtocols:
    """Supported Web Protocols."""

    HTTP = "http"
    HTTPS = "https"
    WEBSOCKETS = "websockets"
    WS = "ws"

    VALID_PROTOCOLS = (HTTP, HTTPS, WEBSOCKETS, WS)


# Specify current valid application services.
class ApplicationServices:
    """Current Application Services."""

    LDAP = "LDAP"
    SSO = "SSO"

    VALID_SERVICES = (LDAP, SSO)
    SERVICE_PATH_PREFIX = "v1/svc"


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-^b*l-)$pynjctby)8oa!4fvmj(xv&vtut5%vs02qqm$=)dnng3"
)

# SECURITY WARNING: don't run with debug turned on in production!
CONTAINER_PASSWORD = os.getenv("PASSWORD", "pa$$word123")

############################################
## DEPLOYMENT/BUILD ENVIRONMENT VARIABLES ##
############################################

# Specify the build for the application, default to development.
BUILD = os.getenv("BUILD", ApplicationBuild.DEVELOPMENT)
if BUILD not in ApplicationBuild.VALID_BUILDS:
    BUILD = ApplicationBuild.DEVELOPMENT


#######################################
## SERVER HOST ENVIRONMENT VARIABLES ##
#######################################

# Set the scheme, host, & port.
# Scheme defaults to https.
SCHEME = os.getenv("SCHEME", WebProtocols.HTTPS)
if SCHEME not in WebProtocols.VALID_PROTOCOLS:
    SCHEME = WebProtocols.HTTPS
SERVER_HOST = os.getenv("SERVER_HOST", "your-server-name")
SERVER_PORT = os.getenv("SERVER_PORT", "your-server-port")
WEB_HOST = os.getenv("WEB_HOST", "your-web-host")
WEB_PORT = os.getenv("WEB_PORT", "your-web-port")


#############################
## DJANGO SETTINGS CONFIGS ##
#############################

# Set DEBUG=True if BUILD is not production.
DEBUG = BUILD != ApplicationBuild.PRODUCTION

# Ensure that the default admin list is kept up to date.
DEFAULT_ADMINS = "Michael.C.Mullings@l3harris.com;"
# These admins will receive an email if the application
# encounters an error.
ADMINS_FROM_ENV = os.getenv("ADMINS", DEFAULT_ADMINS).split(";")
ADMINS_VALUES = [
    admin.strip() for admin in set(ADMINS_FROM_ENV) - {""} if len(admin.strip())
]
ADMINS = [(admin[: admin.rindex("@")], admin) for admin in ADMINS_VALUES]

# Set default date format. ex. January 1, 2025.
DATE_FORMAT = "F j, Y"
# Set default datetime format. ex. January 1, 2025 12:00 a.m.
DATETIME_FORMAT = "F j, Y P"

# Set default FROM email address for application.
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "pmx@l3harris.com")

# Set an upper size limit on file kept in memory.
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.harris.com"
EMAIL_PORT = 25

LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "en-us")

###########################
## DJANGO LOGGING CONFIG ##
###########################

SERVER_LOG_LEVEL_DEBUG = "DEBUG"
SERVER_LOG_LEVEL_INFO = "INFO"
SERVER_LOG_LEVEL_WARN = "WARNING"
SERVER_LOG_LEVEL_ERROR = "ERROR"
SERVER_LOG_LEVEL = os.getenv(
    "SERVER_LOG_LEVEL", SERVER_LOG_LEVEL_DEBUG if DEBUG else SERVER_LOG_LEVEL_ERROR
)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "verbose": {
            "format": (
                "[{asctime}] {levelname} [{pathname}] - "
                "{module}::{funcName}:{lineno} - {message}"
            ),
            "style": "{",
        },
        "simple": {
            "format": (
                "[{asctime}] {levelname} - {module}::{funcName}:{lineno} - {message}"
            ),
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": SERVER_LOG_LEVEL,
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": SERVER_LOG_LEVEL_ERROR,
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
        "rq_console": {
            "level": "DEBUG",
            "class": "rq.logutils.ColorizingStreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "mail_admins"],
            "level": SERVER_LOG_LEVEL,
        },
        "rq.worker": {"handlers": ["rq_console"], "level": "DEBUG"},
        # The below acts as a sort of catch-all logger.
        "": {"handlers": ["console"], "level": os.getenv(SERVER_LOG_LEVEL, "INFO")},
    },
}

# Set to True to redirect all requests to HTTPS.
SECURE_SSL_REDIRECT = os.getenv("SERVER_SECURE_SSL_REDIRECT", "False").title() == "True"

# Set FROM email address for emails sent to admins.
SERVER_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "pmx@l3harris.com")

# Set session lifetime to 2 days.
SESSION_COOKIE_AGE = 172800

##############################
## DJANGO EXTENSIONS CONFIG ##
##############################

EXPORT_EMAILS_ORDER_BY = ["last_name", "first_name", "email"]
EXPORT_EMAILS_FIELDS = ["last_name", "first_name", "email"]
EXPORT_EMAILS_FULL_NAME_FUNC = None

GRAPH_MODELS = {
    "all_applications": True,
    "group_models": True,
}

NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8888",
    "--allow-root",
    "--no-browser",
]

SHELL_PLUS = "ipython"
SHELL_PLUS_PRINT_SQL = True

IPYTHON_ARGUMENTS = [
    "--ext",
    "django_extensions.management.notebook_extension",
    "--debug",
]

IPYTHON_KERNEL_DISPLAY_NAME = f"{APP_NAME} Shell-Plus"

if DEBUG:
    os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

############################################
## ADFS SSO SERVICE ENVIRONMENT VARIABLES ##
############################################

# Ensure that the default origin is kept up to date.
DEFAULT_SSO_ORIGIN = "https://uspby1lnhdped03.gcsd.harris.com:43339"

# SCHEME://HOST:PORT of SSO service.
SSO_ORIGIN = os.getenv("SSO_ORGIN", DEFAULT_SSO_ORIGIN)

# SSO service reverse URL.
SSO_SERVICE_APP_URL = f"{SSO_ORIGIN}/app/{APP_NAME}"

# Default dev user.
SSO_DEVELOPMENT_USER = {
    "first_name": os.getenv("SSO_DEVELOPMENT_USER_FIRST_NAME", "DEV"),
    "last_name": os.getenv("SSO_DEVELOPMENT_USER_LAST_NAME", "USER"),
}

# Request header key for SSO dev user.
SSO_DEVELOPMENT_USER_REQUEST_HEADERS_KEY = "SSO-Development-User"

# Encryption Key used to decrypt SSO service auth data.
SSO_SERVICE_ENCRYPTION_KEY = os.getenv("SSO_SERVICE_ENCRYPTION_KEY", "secret-key")

# Trusted hosts for cross site requests.
CSRF_TRUSTED_ORIGINS = [
    f"{SCHEME}://{WEB_HOST}:{WEB_PORT}",
]

########################################
## LDAP SERVICE ENVIRONMENT VARIABLES ##
########################################

# Ensure that the default endpoint is kept up to date.
DEFAULT_LDAP_SEARCH_ENDPOINT = "http://uspby1lnhdped03:8822/ldap/employees/cac"
LDAP_SEARCH_ENDPOINT = os.getenv("LDAP_SEARCH_ENDPOINT", DEFAULT_LDAP_SEARCH_ENDPOINT)

# Construct origin for frontend web app.
WEB_APP_ORIGIN = f"{SCHEME}://{WEB_HOST}:{WEB_PORT}"
# Add local, l3harris, and frontend web app domains.
ALLOWED_HOSTS = [
    "api",
    "web",
    "localhost",
    "127.0.0.1",
    "0.0.0.0",
    ".cs.myharris.net",
    ".gcsd.harris.com",
    ".rootforest.com",
    WEB_APP_ORIGIN,
]

if BUILD in {ApplicationBuild.DEVELOPMENT, ApplicationBuild.TEST}:
    ALLOWED_HOSTS += [
        "testserver",
    ]

############################
## APPLICATION DEFINITION ##
############################

# Set all custom django apps here.
CUSTOM_APPS: list[str] = ["users", "directory", "analytics", "preferences", "request"]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "debug_toolbar",
    "django_extensions",
    "django_rq",
    "rest_framework",
    *CUSTOM_APPS,
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "manager.middleware.DevelopmentAuthenticationMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.cache.FetchFromCacheMiddleware",
]

ROOT_URLCONF = "manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "NAME": "jinja",
        "DIRS": [os.path.join(BASE_DIR, "manager/jinja2/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "environment": "manager.jinja2.environment.JinjaEnvironment",
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "NAME": "django",
        "DIRS": [os.path.join(BASE_DIR, "manager/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "manager.templates.context_processors.app",
            ],
            "debug": DEBUG,
        },
    },
]

WSGI_APPLICATION = "manager.wsgi.application"

ASGI_APPLICATION = "manager.asgi.application"

##############
## DATABASE ##
##############
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": db.config.BASE.ENGINE,
        "NAME": db.config.BASE.NAME,
        "USER": db.config.BASE.USER,
        "PASSWORD": db.config.BASE.PASSWORD,
        "HOST": db.config.BASE.HOST,
        "PORT": db.config.BASE.PORT,
        "TEST": db.config.BASE.TEST,
        "ATOMIC_REQUESTS": db.config.BASE.ATOMIC,
    }
}

if BUILD == ApplicationBuild.TEST:
    MIGRATE = False
    FIXTURE_DIRS = (BASE_DIR,)

# Set the list of database routers with path.to.router
# Routers direct reads, writes, etc to the appropriate
# database.
DATABASE_ROUTERS: list[str] = []

###########
## CACHE ##
###########
# https://docs.djangoproject.com/en/5.0/topics/cache/#redis

SECONDS_IN_A_MINUTE = 60
CACHES = {
    "default": {
        "BACKEND": cache.config.CACHE.BACKEND,
        "LOCATION": [
            (
                f"redis://default:{cache.config.CACHE.PASSWORD}"
                f"@{cache.config.CACHE.HOST}:{cache.config.CACHE.PORT}"
            ),
        ],
        "KEY_PREFIX": f"cache.{APP_NAME}",
        "TIMEOUT": 15 * SECONDS_IN_A_MINUTE,
    }
}

##########################
## DJANGO DEBUG TOOLBAR ##
##########################

if DEBUG:
    INTERNAL_IPS = ["0.0.0.0", "127.0.0.1", "localhost"]


def show_django_debug_toolbar(request: HttpRequest) -> bool:
    """Determine whether to show the django debug toolbar
    on Django.contrib.admin site. Toolbar provides helpful
    insights into the health and performance of your application."""

    if DEBUG and BUILD == ApplicationBuild.DEVELOPMENT:
        return True
    return False


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "manager.settings.show_django_debug_toolbar"
}

####################
## CHANNELS CACHE ##
####################

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": cache.config.CHANNEL.BACKEND,
        "CONFIG": {
            "hosts": [
                {
                    "address": (
                        f"redis://default:{cache.config.CHANNEL.PASSWORD}"
                        f"@{cache.config.CHANNEL.HOST}:{cache.config.CHANNEL.PORT}"
                    ),
                }
            ],
            "prefix": f"asgi.{APP_NAME}",
            "expiry": 1 * SECONDS_IN_A_MINUTE,
            "symmetric_encryption_keys": [SECRET_KEY],
        },
    },
}

################
## TASK QUEUE ##
################

RQ_QUEUES = {
    "default": {
        "HOST": f"{cache.config.TASKQUEUE.HOST}",
        "PORT": f"{cache.config.TASKQUEUE.PORT}",
        "DB": 0,
        "USERNAME": "default",
        "PASSWORD": f"{cache.config.TASKQUEUE.PASSWORD}",
        "DEFAULT_TIMEOUT": 360,
    }
}

#########################
## PASSWORD VALIDATION ##
#########################
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation"
            ".UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

if BUILD not in [ApplicationBuild.DEVELOPMENT, ApplicationBuild.TEST]:
    # Add settings for Django REST authentication
    REST_FRAMEWORK = {
        "DEFAULT_PERMISSION_CLASSES": (
            "rest_framework.permissions.IsAuthenticatedOrReadOnly",
        ),
    }

##########################
## INTERNATIONALIZATION ##
##########################
# https://docs.djangoproject.com/en/5.0/topics/i18n/

TIME_ZONE = os.getenv("SERVER_TIME_ZONE", "US/Eastern")

USE_I18N = True

USE_TZ = True

############################################
## STATIC FILES (CSS, JavaScript, Images) ##
############################################
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "v1/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "manager/storage/static"),
]

#################
## MEDIA FILES ##
#################

MEDIA_URL = "v1/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "manager/storage/media")

####################################
## DEFAULT PRIMARY KEY FIELD TYPE ##
####################################
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
