# Generated by Django 5.0.2 on 2024-08-12 17:27

import django.db.models.deletion
from users.models import Segment
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=Segment.SegmentChoices.get_segment_choices,
                        max_length=512,
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(blank=True, default="", max_length=10)),
                (
                    "middle_initial",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("unix_name", models.CharField(blank=True, default="", max_length=15)),
                ("job_title", models.CharField(blank=True, default="", max_length=256)),
                (
                    "job_function",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "job_family",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "job_category",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("job_level", models.IntegerField(default=None, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("status", models.CharField(blank=True, default="", max_length=256)),
                ("division", models.CharField(blank=True, default="", max_length=256)),
                (
                    "business_unit",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("location", models.CharField(blank=True, default="", max_length=256)),
                (
                    "citizenship",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        db_column="segment",
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.segment",
                    ),
                ),
            ],
        ),
    ]
