# Generated by Django 5.0.2 on 2024-08-12 17:30
import logging

from django.db import DatabaseError, IntegrityError, migrations, transaction

from users.models import Segment

LOGGER = logging.getLogger(__name__)


SAS_DESCRIPTION = (
    "Space and Airborne Systems is a leading provider of full mission solutions"
    " as a prime and subsystem integrator in the space, airborne and cyber domains."
    " We provide top-tier capabilities in the design, development, integration, "
    "production and sustainment of major weapons systems for defense primes"
    " and national security, civil government and international customers."
)
IMS_DESCRIPTION = (
    "Integrated Mission Systems is a leading provider of differentiated mission"
    " capabilities and prime systems integration for the air, land and sea domains."
    " We deliver top-tier capabilities in the design, development, integration,"
    " production, modernization and sustainment of intelligence, surveillance,"
    " and reconnaissance (ISR), passive sensing and targeting, electronic attack,"
    " autonomy, power and communications, networks and sensors for national"
    " security and international customers."
)
CS_DESCRIPTION = (
    "Communication Systems enables warfighters across all domains with solutions"
    " critical to mission success even in the most contested environments."
    " We are a leading provider of resilient communications solutions for"
    " the U.S. Department of Defense (DoD), international, federal and"
    " state agency customers."
)
AR_DESCRIPTION = (
    "Aerojet Rocketdyne is a leading provider of propulsion, power and"
    " armament products and systems to the U.S. government, including"
    " the DoD, National Aeronautics and Space Administration (NASA)"
    " and major aerospace and defense prime contractors."
)

SEGMENTS_MAP = {
    Segment.SegmentChoices.SPACE_AND_AIRBORNE_SYSTEMS: SAS_DESCRIPTION,
    Segment.SegmentChoices.INTEGRATED_MISSION_SYSTEMS: IMS_DESCRIPTION,
    Segment.SegmentChoices.COMMUNICATION_SYSTEMS: CS_DESCRIPTION,
    Segment.SegmentChoices.AEROJET_ROCKETDYNE: AR_DESCRIPTION,
}


def create_initial_segments(apps, schema_editor):
    """
    Create the initial segments for L3Harris Technologies, Inc.
    as of 07/23/2024
    """

    SegmentModel = apps.get_model("users", "Segment")

    try:
        LOGGER.info("Creating initial segments...")

        with transaction.atomic():
            for segment_name, segment_description in SEGMENTS_MAP.items():
                SegmentModel.objects.using(schema_editor.connection.alias).create(
                    name=segment_name, description=segment_description
                )
        LOGGER.info("Successfully created initial segments.")
    except (DatabaseError, IntegrityError) as exc:
        LOGGER.error(f"Failed to create all of the segments in migration: {exc}")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_initial_segments)]
