# Generated by Django 5.0.2 on 2024-08-26 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request", "0001_initial"),
        ("users", "0002_initialize_segment_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=512, unique=True)),
                ("description", models.TextField()),
                ("level", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "role",
                "verbose_name_plural": "roles",
                "db_table_comment": (
                    """
                    `Role` represents an access role in the system. Access
                    roles are used in role-based authorization to determine
                    permissions within the application. A `Role` either has
                    all permissions for that role or none.

                    A `Role` includes:
                        * id (int): An auto-generated number managed by the database.
                        * name (models.CharField): Name of the role.
                        * description (models.TextField): A description of the role's
                            purpose and authority.
                        * level (models.PositiveIntegerField): An immutable numerical
                            representation of that authority.
                        * created (models.DateTimeField): The date & time this `Role`
                            was created.
                    """
                ),
                "ordering": ["level"],
                "default_related_name": "roles",
                "indexes": [
                    models.Index(fields=["level"], name="role_level"),
                    models.Index(fields=["name"], name="role_name"),
                    models.Index(fields=["id"], name="role_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_granted_date", models.DateTimeField(default=None, null=True)),
                ("access_revoked_date", models.DateTimeField(default=None, null=True)),
                (
                    "stage",
                    models.ManyToManyField(
                        db_table="users_access_stages", to="request.stage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.role"
                    ),
                ),
            ],
            options={
                "verbose_name": "access",
                "verbose_name_plural": "accesses",
                "db_table_comment": (
                    """
                    `Access` represents an individual access within the
                    system associated with a role. The application uses
                    accesses as part of its role-based authorization to
                    grant permissions and privileges to its users. If an
                    access is revoked as indicated by `access_revoked_date`,
                    all permissions and privileges are also revoked and this
                    record is merely kept for historical purposes.

                    An `Access` includes:
                        * id (int): An auto-generated number managed by the database.
                        * user (contrib.auth.models): BI Portal user.
                        * role (users.models.Role): Role of the user which confers system
                            permissions and access to the user.
                        * access_granted_date (models.DateTimeField): The date & time the user was
                            granted access with this particular role.
                        * access_revoked_date (models.DateTimeField): The date & time this access was
                            revoked for this particular role.
                        * stage (models.ManyToManyField[request.models.Stage]): The stage at which
                            the user with this `Access` is permitted to submit a `Disposition`.
                    """
                ),
                "ordering": ["id"],
                "default_related_name": "accesses",
                "indexes": [
                    models.Index(fields=["role"], name="access_role"),
                    models.Index(fields=["user"], name="access_user"),
                    models.Index(fields=["id"], name="access_id"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="access",
            constraint=models.UniqueConstraint(
                fields=("user", "role", "access_granted_date"),
                name="user_access_on_granted_date",
            ),
        ),
    ]
