# Generated by Django 5.0.2 on 2025-05-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0003_modify_thumbnail_path"),
        ("users", "0003_role_access_access_user_access_on_granted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="access",
            name="subfunctions",
            field=models.ManyToManyField(
                db_table="users_access_subfunctions", to="directory.subfunction"
            ),
        ),
    ]
