# Generated by Django 5.0.2 on 2025-05-14 19:47

import logging
from typing import cast

from django.db import migrations

from directory import models as DirectoryModels
from users import models as UsersModels


def add_subfunctions_to_accesses(apps, schema_editor):
    """For all existing `Access` records, populate their subfunctions
    with those related to the `Resource`s for the `Request` records that
    they originated."""

    LOGGER = logging.getLogger(__name__)

    Access = cast(UsersModels.Access, apps.get_model("users", "Access"))
    Resource = cast(DirectoryModels.Resource, apps.get_model("directory", "Resource"))
    SubFunction = cast(
        DirectoryModels.SubFunction, apps.get_model("directory", "SubFunction")
    )

    LOGGER.info("Updating existing Accesses with appropriate SubFunctions...")

    for record in Access.objects.all():
        requests = record.requests.all()
        resource_ids = requests.values_list("resource__id", flat=True)
        subfunction_ids = Resource.objects.filter(id__in=resource_ids).values_list(
            "subfunctions__id", flat=True
        )
        subfunctions = SubFunction.objects.filter(id__in=subfunction_ids)
        record.subfunctions.set(subfunctions)

    row_count = Access.objects.count()
    log_msg = f"Updated {row_count} Access records..."
    LOGGER.info(log_msg)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_subfunctions_relation_to_access"),
    ]

    operations = [
        migrations.RunPython(add_subfunctions_to_accesses),
    ]
