# Generated by Django 5.0.2 on 2026-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_subfunctions_to_accesses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="uid",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
