# Ensure to set PYTHONPATH to ./api/src
# Run mypy with mypy --no-incremental --config=api/mypy.ini api/src

[mypy]
plugins = 
    mypy_django_plugin.main

# Allows variables to be redefined with an arbitrary type, as
# long as the redefinition is in the same block and nesting
# level as the original definition.
allow_redefinition = True
# Type-checks the interior of functions without type annotations.
check_untyped_defs = True
# Comma separated list of ignored error codes.
disable_error_code = import-untyped,no-redef
# Disallows defining functions without type annotations
# or with incomplete type annotations.
disallow_untyped_defs = True
# Prohibit equality checks, identity checks, and container
# checks between non-overlapping types.
strict_equality = True
# Shows errors for missing return statements.
warn_no_return = True
# Shows a warning when returning a value with type Any from
# a function declared with a non-Any return type.
warn_return_any = True
# Shows a warning when encountering any code inferred to
# be unreachable or redundant. 
warn_unreachable = True
# Warns about unneeded # type: ignore comments.
warn_unused_ignores = True

[mypy.plugins.django-stubs]
django_settings_module = manager.settings

# Turn off mypy for all django migration packages via naming convention.
[mypy-*.migrations.*]
ignore_errors = True

[mypy-*.Resource.Resource]
ignore_errors = True